### PR TITLE
Add suport for CMake to get ChibiOS from GitHub

### PR DESCRIPTION
**Pull request by josesimoes**
- insted of SVN as it was doing before

Signed-off-by: José Simões <jose.simoes@eclo.solutions>

### CODE REVIEW

**Comment by josesimoes** [comment]
Conflict solved.

**Comment by cw2** [comment]
Please prefer rebase to back-merge.

**Comment by josesimoes** [comment]
> Please prefer rebase to back-merge.

Could you please point me to a GitHub help or article to illustrate you are asking?

**Comment by cw2** [comment]
For example https://help.github.com/articles/using-git-rebase-on-the-command-line/, but much better explanation is https://www.atlassian.com/git/tutorials/merging-vs-rebasing.

The key difference is the existence of the merge commit - if there was a change in `dev-cmake-build` after your commit, you can either merge `dev-cmake-build` into your feature branch (creating a merge commit and bringing all the history with it), or you can rebase - which means re-applying your changes to the actual state of `dev-cmake-build` (git does that automatically for you).

**Comment by cw2** [comment]
(it is safe to rebase pull request branch - it would cause problems only if it was shared with other people who were actually working on their copies in parallel)

**Pull request merged**
