### PR TITLE
Include ChibiOS download in Dockerfile.AzureRTOS

### PR DESCRIPTION
**Pull request by networkfusion**
## Description
Adds the SVN download.

## Motivation and Context
AzureRTOS currently requires the ChibiOS HAL.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by Ellerbach** [comment]
Thanks. In that case, you need as well to bump the container version as well. It's due every time someone is changing the Dockerfile.

**Comment by josesimoes** [comment]
@Ellerbach I was hitting the push button as you were typing. 😆

**Comment by Ellerbach** [comment]
> I was hitting the push button as you were typing. 😆

So you are due to a new PR just to bump the container version :-D

**Comment by josesimoes** [comment]
Nope! Bumping the version _was_ the commit 
👀  0cccc07

**Comment by networkfusion** [comment]
For what ever reason, the GH action is showing as failed... I cannot see anything that would cause it from this PR...

**Comment by Ellerbach** [comment]
Most likely coming from `git svn clone`
How did you test it? Are you sure SVN is properly installed with git?

**Comment by josesimoes** [comment]
Fixed now. That container was indeed missing git-svn and subversion packages.

**Pull request merged**
