### PR TITLE
Fix time conversion issues in PAL events

### PR DESCRIPTION
**Pull request by martin-kuhn**
## Description
Debug checks showed, that the chVTSet method is always called with a delay of zero, which should not be done.
The delay of zero was caused by dividing the ticks value by TIME_CONVERSION__TO_MILLISECONDS (=10000) which is not necessary. The compareValueTicks is already in CMSIS Ticks there, which is equal to milliseconds.
We also have to use the HAL_Time_CurrentSysTicks() method wherever the value is in CMSIS ticks instead of the HAL_Time_CurrentTime() method which returns a value in .NET ticks.

## How Has This Been Tested?
This has been tested on a custom STM32F427 based MCU board.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: Martin Kuhn martin.kuhn@csa.ch

### CODE REVIEW

**Comment by josesimoes** [comment]
Looks good on infinite loop testing.

Here's s screeshot from the scope output for a toggle on an infinite loop with 125ms.
image

**Comment by josesimoes** [comment]
Running the timer sample shows some curious results:

1. Running **with** debugger attached it blinks the complete sequence as expected.

2. Running **without** debugger attached it blinks only 3 timer and then the board reboots.

🤔 this smells like a watchdog issue....

**Comment by josesimoes** [comment]
Care to merge the latest changes from develop branch please so this can be merged?

**Comment by martin-kuhn** [comment]
Yes, it's done.
Could you solve the timer problem?

**Pull request merged**
