### PR TITLE
StorageFile DateTime Heap corruption fix

### PR DESCRIPTION
**Pull request by AdrianSoundy**
## Description
When we updated a dateTime in the StorageFile object it corrupted the heap because code assumes its its referencing a DateTime field but in this case it is a DATA_OBJECT with reference to DATATYPE_VALUETYPE of class DateTime 

Changed code to use the corlib function-
Library_corlib_native_System_DateTime::GetValuePtr( CLR_RT_HeapBlock& ref ) method to get ptr to DateTime
This now seems to work OK

So far only done for ESP32 will probably need same change for other platforms. 

Please review, if ok i'll do other platforms

## Motivation and Context
reported by @TheFLC on Discord

## How Has This Been Tested?
Simple test program crashed on Heap compact, haven't as yet run samples
```
		public static void Main()
		{
			Debug.WriteLine("Hello from nanoFramework!");
			{

				var InternalDevices = Windows.Storage.KnownFolders.InternalDevices;
				StorageFolder spiffDevice = InternalDevices.GetFolders()[0];

				StorageFile sf = spiffDevice.CreateFile("serial.txt", CreationCollisionOption.ReplaceExisting);

                                Debug.WriteLine($"dateTime:{sf.DateCreated}");

				sf.Delete();
			}

			Debug.WriteLine("CreateFile");

			nanoFramework.Runtime.Native.GC.Run(true);

			Debug.WriteLine("Heap compacted");

			Thread.Sleep(Timeout.Infinite);
		}
```

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by andybeetz** [comment]
I also found a fix by using:

dateFieldRef.SetInteger((CLR_UINT64)GetFileTimeFromPath(workingPath));

Is there much difference between the two approaches?

**Review by josesimoes — APPROVED** [review]
Makes perfect sense! Good job.

**Comment by josesimoes** [comment]
> I also found a fix by using:
> 
> dateFieldRef.SetInteger((CLR_UINT64)GetFileTimeFromPath(workingPath));
> 
> Is there much difference between the two approaches?
> 
> Also! StorageFile.cpp also needs the fix.

That works too. But Adrian approach has a better check for and dealing with null pointers and such.
Not that that is expected to happen, but it can.

**Comment by josesimoes** [comment]
> Also! StorageFile.cpp also needs the fix.
@AdrianSoundy when you're porting this to the other platforms please take this into account.

**Comment by AdrianSoundy** [comment]
I tested the approach of 
`dateFieldRef.SetInteger((CLR_UINT64)GetFileTimeFromPath(workingPath));`
But it doesn't work. You don't get a heap problem but if you try to print out dataTime from storageFile object it gives you wrong type exception.
@andybeetz @josesimoes

**Review by josesimoes — APPROVED** [review]
LGTM!

**Comment by AdrianSoundy** [comment]
NXP is using a different method to save datetime by creating an instance of DateTime updating ticks then saving it to object ref.
Probably works but i'll update it anyway so all platforms consistent. Also moving code to separate method reduces code size.

**Pull request merged**
