### PR TITLE
Remove wait from Monitor_Reboot

### PR DESCRIPTION
**Pull request by josesimoes**
## Description
- Remove wait from Monitor_Reboot

## Motivation and Context
- After the improvement in deploy workflow (VS extension v0.3.8.58) this is not required anymore
- Reverts #2b1f18f
- Fixes nanoFramework/Home#316

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Signed-off-by: josesimoes <jose.simoes@eclo.solutions>

### CODE REVIEW

**Comment by josesimoes** [comment]
@AdrianSoundy please validate this.
After the improvement in deployment (VS extension v0.3.8.58) I believe that this _pause_ is not required anymore.

I've traced the root for the Console.Writeline() to this change. 
This pause is causing an awkward CLR reboot behaviour which is clearing the `c_fDebugger_Enabled` flag which, in turn, causes that the debugger output messages being skipped because the code wrongly _thinks_ that there is no debugger attached. 
Here: https://github.com/nanoframework/nf-interpreter/blob/e41c75ede58636eceeaab7529c5170641d494700/src/CLR/Diagnostics/Info.cpp#L201

**Comment by piwi1263** [comment]
This is looking promising:
image

but the SWO output is gone, intended ??

**Comment by josesimoes** [comment]
Not intended... A side effect of the string being " processed" in the call to the debugger output before reaching there...
I suspect that, as it is, you'll probably see one or the other.

**Comment by josesimoes** [comment]
After the improvements in the debugger engine attachment brought with VS extension 0.3.8.61 this doesn't seem to be required anymore.

**Pull request closed without merging**
