### PR TITLE
Rework ESP32 serial update

### PR DESCRIPTION
**Pull request by AdrianSoundy**
## Description
- Rework of ESP32 serial.
- Fixes problem with IDF 3.3.1 not firing events for RX.

## Motivation and Context
- Resolves nanoFramework/Home#610.
- Resolves nanoFramework/Home#612.

## How Has This Been Tested?
Simple test program. With read/write only and events

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by josesimoes** [comment]
Hi @MikeRogers0,

Despite having add the words to the ignore collection, I'm still seeing them reported as errors...
I'm refering to the "Uart" word in the annotation on this PR. Not sure if it needs to be added in all possible variations, which would be "Uart", "uart" and "UART"...

PS: btw, thank you so much for this great tool! 👏 😃

**Comment by MikeRogers0** [comment]
@josesimoes  Looking into this now :)

> Despite having add the words to the ignore collection

https://github.com/nanoframework/nf-interpreter - When I look in here, I'm not seeing a `.typo-ci.yml` file :/ Is it in another PR?

**Comment by josesimoes** [comment]
> @josesimoes Looking into this now :)
> 
> > Despite having add the words to the ignore collection
> 
> https://github.com/nanoframework/nf-interpreter - When I look in here, I'm not seeing a `.typo-ci.yml` file :/ Is it in another branch PR?

It's on the organization .github repo. I thought it was allowed to put it there... maybe I'm mistaken...

**Comment by MikeRogers0** [comment]
@josesimoes My apologies, right now it only looks in the matching repository. 

I've added supporting `.github` repositories as a fallback to my TODO list! That would be pretty awesome!

**Comment by josesimoes** [comment]
@MikeRogers0 undestood.
Yes, that would be awesome for organizations that have a bunch of repos, like this one! 😉 
Thanks.

**Pull request merged**
