### PR TITLE
Removes duplicate `elseif`

### PR DESCRIPTION
**Pull request by networkfusion**
## Description
The code `elseif(RTOS_FREERTOS_CHECK)` is duplicated in CMakeLists.txt. It was likely caused by a merge.

## Motivation and Context
Code fix

## How Has This Been Tested?
If the build pipeline still works, then no issues are caused.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by josesimoes — APPROVED** [review]
LGTM

**Comment by networkfusion** [comment]
Unless I got it the wrong way around of course 😓

**Review by josesimoes — CHANGES_REQUESTED** [review]
I take it back... 😊 

Doesn't look *that* good.

The if block to be removed is the bigger one, not this.
It's part of a rework that I've started and aims to put everything relevant to the platform inside it's folder.
This has been done for FreeRTOS but for some reason the *leftover* code was there. Probably because of a bad merge...

**Comment by networkfusion** [comment]
Ok, I will leave this for you to solve, feel free to close this PR if it is being handled by your refactoring. Since the first `elseif` is the correct one, that means the code will not be hit for the moment.

**Comment by josesimoes** [comment]
Done!

**Pull request merged**
