### PR TITLE
[WIP] nanoCLR

### PR DESCRIPTION
**Pull request by cw2**
Initial NETMF code import, converted to Visual C++ projects, and stubs are used for simple feature configuration in the test application.

Removed endian conversion (swapping) code

In [a rare] case the endian conversion is necessary, it should be done on the PC side.

Removed JIT code

### CODE REVIEW

**Comment by cw2** [comment]
Basically all the features are stubbed out. To check the nanoCLR test application

1. Open `targets\os\win32\netmf\MFConsoleApplication\MFConsoleApplication.sln` in Visual Studio 2015 (NETMF)
2. Open `targets\os\win32\nanoCLR.sln` in Visual Studio 2017,
3. Select `Debug x86` configuration,
4. Build & run.

Notes
- NETMF (pe) assembly and references are loaded in `Settings::Load()`, `CLRStatup.cpp` line 131,
- Diagnostic output does not print anything (not ported yet),
- CLR features are configured via `#pragma comment(lib...)` in `main.cpp` - this is going to be replaced with compile-time directives (#ifdef), there will be no stubs.

**Comment by cw2** [comment]
Next steps (in no particular order):

- Rename TINY to nano
- Replace stubs with compile-time directives,
- Implement HAL
- Convert build to CMake
    - CMake can generate VS projects
- Unify wire protocol, messaging and commands implementation

**Comment by josesimoes** [comment]
Wow! All this is a single strike.
Very well done!!!

**Comment by cw2** [comment]
> All this is a single strike.

Courtesy of git squash :)

**Pull request merged**
