### PR TITLE
Create .gitattributes

### PR DESCRIPTION
**Pull request by networkfusion**
## Motivation and Context

When using the dev container, it can convert all files to use linux file endings, which creates a lot of potential changes when creating a PR.
Adding a `.gitattributes` file ensures the changes are kept as windows eol.

See here for further details: https://code.visualstudio.com/docs/remote/troubleshooting#_resolving-git-line-ending-issues-in-wsl-resulting-in-many-modified-files

## Screenshots
image

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by josesimoes** [comment]
Interesting and handy for sure!
Why no go with the full suggestion on the URL above?

```text
* text=auto eol=lf
*.{cmd,[cC][mM][dD]} text eol=crlf
*.{bat,[bB][aA][tT]} text eol=crlf
```

**Comment by networkfusion** [comment]
> Interesting and handy for sure! Why no go with the full suggestion on the URL above?
> 
> ```
> * text=auto eol=lf
> *.{cmd,[cC][mM][dD]} text eol=crlf
> *.{bat,[bB][aA][tT]} text eol=crlf
> ```

These are un-necessary as have the expected line endings. Adding rules are only needed if we need to filter to a different line ending.

**Comment by networkfusion** [comment]
With the file added:

image

**Comment by Ellerbach** [comment]
> These are un-necessary as have the expected line endings. Adding rules are only needed if we need to filter to a different line ending.

Yes and not, depends how you create the files. If it doesn't hurt, go for the full suggestion! And I usually have 2 sessions of VS Code open: one with the dev container, and another one without. And yes, great finding. Looks good to me!

**Review by Ellerbach — APPROVED** [review]
Add the rest of the recommendation as it should not hurt and will keep things clean.
Note that if we have to run scripts on Linux, an exception should be added for those files.

**Comment by networkfusion** [comment]
> Add the rest of the recommendation as it should not hurt and will keep things clean. Note that if we have to run scripts on Linux, an exception should be added for those files.

So a better tact here would be to implement:

```
* text=auto eol=crlf
*.{sh} text eol=lf
```

**Comment by networkfusion** [comment]
Extra note, I think there is some confusion and I will try and explain...

By default, our repo uses Windows line endings for all files (`CRLF`). The example I posted in the PR description utilises linux line endings (`LF`).

We want to do the opposite, unless we want to do a mass repo update to switch all files.

**Comment by Ellerbach** [comment]
> Unless we want to convert the whole repo to linux line endings and have CRLF only where required...

we definitelt don't want to convert all :-) So yes for the .sh soecific ending!

**Comment by networkfusion** [comment]
> > Unless we want to convert the whole repo to linux line endings and have CRLF only where required...
> 
> we definitelt don't want to convert all :-) So yes for the .sh soecific ending!

Okay, done.

**Pull request merged**
