### PR TITLE
Cleanup of UART driver for MIMXRT1062.

### PR DESCRIPTION
**Pull request by morali**
Implemented read by using StreamBuffers from FreeRTOS. One task for receiving data and DMA interrupt. Added example LPUART3 pins for testing purpose.

## Motivation and Context
Rework of Uart read was needed. I simplified functions and rewrote uart read function.

## How Has This Been Tested?
Tested using SerialCommunication scenarios acquired from nanoFramework repository.

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Signed-off-by: moralil <jeremi.jasinski@gmail.com>

### CODE REVIEW

**Comment by josesimoes** [comment]
@morali nice to see that you're making good progress on this.

This PR has a lot more changes and touches a lot of files that I'm sure is way more than the real changes.
I think this is because you are using the "develop-freertos-iMXRT10xxx" branch to work on the features instead of working on a separate branch.

The recommended approach is to work on a "feature branch" and pull whatever changes are coming from the "development" branch. When you are done, you should rebase it so that ONLY the relevant changes show on the PR. 


Please check the contributing guide [here](https://docs.nanoframework.net/content/contributing/contributing-workflow.html#suggested-workflow).

**Comment by morali** [comment]
Initialy there were 4 commits, idk how did it changed to this number of files. 
I think it's fixed now, so please check.
Thanks!

**Comment by josesimoes** [comment]
@morali the CLA bot is complaining about your GitHub user... maybe you've changed the email on your account or in one of the commits... not sure exactly why. Please check.

**Comment by morali** [comment]
@josesimoes I think it's all good now.  :)

**Comment by josesimoes** [comment]
CLA check passed! It's good to go.

**Pull request merged**
