### PR TITLE
Updating dev container for ChibiOS using svn

### PR DESCRIPTION
**Pull request by Ellerbach**
## Motivation and Context

- Updating dev container for ChibiOS using svn
- Increased container versions

## How Has This Been Tested?

Locally with source/DockerFile.ChibiOS

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by networkfusion — APPROVED** [review]
LGTM, as long as it still builds the containers for use.

**Comment by networkfusion** [comment]
As a note, it would be preferable to make a further option to just use the specified local folder files if no SVN or Git exists.

**Comment by networkfusion** [comment]
And further, is there any difference between using git svn clone on Windows vs Linux, as that will make it easier for people without SVN tools on their windows install.

**Comment by Ellerbach** [comment]
> As a note, it would be preferable to make a further option to just use the specified local folder files if no SVN or Git exists.

If you do not specify anything, it's uses automatically a clone with the usual process. So it will just work as expected.

**Comment by Ellerbach** [comment]
> And further, is there any difference between using git svn clone on Windows vs Linux, as that will make it easier for people without SVN tools on their windows install.

So far didn't change it, but we can adjust the docs and give the magic command, including in the pipeline. I'll just leave @josesimoes play a bit with that now he has a quick way to clone an svn repo ;-)

**Pull request merged**
