### PR TITLE
Fix PalX ADC config

### PR DESCRIPTION
**Pull request by networkfusion**
## Description

Improves the PalX ADC configuration after input from @gligorov.
It is now able to read the thermistor port correctly.

## Motivation and Context
Temperatures were not working correctly.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by josesimoes** [comment]
Isn't this more than OK to merge?

**Comment by networkfusion** [comment]
@josesimoes although the changes are valid, it needs your expert attention to work out why there are still issues with the ADC channel changes in comparison to the Pal3. I did not think it worth merging before all were working and correct.

**Comment by networkfusion** [comment]
For reference, the test program I used was: https://github.com/networkfusion/orgpal-x-demo/tree/test

**Comment by networkfusion** [comment]
@josesimoes and... I still cannot work out why this PR is building for the wrong boards!

**Comment by josesimoes** [comment]
@networkfusion fixed in #3007 along with other wrong GPIO assignments.
Tested by @gligorov .

**Pull request closed without merging**
