### PR TITLE
Adding support for RMT for ESP32 C3

### PR DESCRIPTION
**Pull request by Ellerbach**
## Description

Adding RMT for ESP32 C3

## Motivation and Context

- Closes nanoFramework/Home#1243

## How Has This Been Tested?

Need to be tested.

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by Ellerbach** [comment]
@MrCSharp22 I've been fixing the build for ESP32 C3 for RMT. I noticed that one of the function is accessing a volatile part of the memory which is not the same on C3. I left if like this for the others at is seems not to break. But ultimately, it should use the function dedicated for this.
I haven't been able to test the fix. So if you have a C3, please do :-) And also if the function works for the rest of the platform, would be millions time better to use it. So we can avoid this issue for the next platform. Again, no way for me to test this now.

**Review by josesimoes — APPROVED** [review]
LGTM! I love the simplicity of the implementation. Thanks for taking the time to look into this and make this happen.

**Comment by MrCSharp22** [comment]
@Ellerbach nice catch! I don't have a C3 yet but I am going to test this branch locally and confirm.

**Comment by Ellerbach** [comment]
I guess, we can merge that one. If not working on C3, we will know it quickly :-) We do have few users waiting for that!

**Review by MrCSharp22 — APPROVED** [review]

**Comment by nagyleventeboldizsar** [comment]
Hello there, Discord @szwiti here. It's working beautifully with FW ESP32_C3-1.8.1.64. Thank you for all!! Kudos to you!

**Comment by MrCSharp22** [comment]
Seems ok on my end. Thanks again @Ellerbach

**Pull request merged**
