### PR TITLE
Recreate work on #2325

### PR DESCRIPTION
**Pull request by networkfusion**
## Description
Work on #2325 and add probable fixes...

* Fixed `CMakePresets.json`
* Moved `Spi_To_Display` to seperate class, as changes were dangerous (for ESP32)!
* ILI9341_240x320_SPI still used, but ILI9341_XXXxYYY_SPI might be better?!
* Driver `STMPE811QTR_I2C` would not work (as is).
* Touch panel changes probably don't work as is, but retained for check.

## Motivation and Context
Lack of input from original contributer...

## How Has This Been Tested?
I dont have a board... Perhaps @piwi1263 has one?

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by josesimoes** [comment]
@networkfusion the CLA was signed for #2325, We should merge it into a branch in our repo and take it from there.

**Comment by networkfusion** [comment]
> @networkfusion the CLA was signed for #2325, We should merge it into a branch in our repo and take it from there.

That might be a good idea, but was struggling with some of the changes that must have occured on a `rebase` and `force push` so thought it easier to just recreate it for the time being, and at least get it buildable again (without affecting other targets)...

**Comment by networkfusion** [comment]
I think I have gone as far as my knowledge now... Currently fails with 
image

And possibily into different PR territory!

**Comment by josesimoes** [comment]
I was looking at this again and there are a few things that need to be addressed.
But we can't "hijack" the original contributor work and just recreated it. Let's merge #2325 into a `develop-` and take it from there OK? This will retain the proper file history and code authorship attribution.

**Pull request closed without merging**
