### PR TITLE
Simplifies naming convention for RTOS targets.

### PR DESCRIPTION
**Pull request by networkfusion**
## Description
Currently all RTOS's use a different name for their target board
this is un-necessary as the RTOS is set.

## Motivation and Context
Optimisation of build system

## How Has This Been Tested?
If the code builds, then no apparent issues caused.

## Types of changes
- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by josesimoes** [comment]
As we are simplifying why not just make TARGET_BOARD? RTOS doesn't add any particular clarification to it...

**Comment by networkfusion** [comment]
Mainly because of the distinction between some source files when searching and that use too similar names, but also for the fact that I am about to add another PR that also makes the RTOS source generic. e.g. 
image
We can simplify further later if required, I am just scared to take a step that will make it hard to support users...

**Comment by networkfusion** [comment]
and would also argue that the targets name is RTOS dependent...

**Comment by josesimoes** [comment]
> and would also argue that the targets name is RTOS dependent (given the fact that it uses a "target" folder).

A long long time ago we've agreed (after endless discussions) to use 'target' as the word for the concept "MCU+stuff around it".  Completely RTOS agnostic. That's why you see the current grouping: targets >> RTOS name >>  target name.
This means that you can have the same **target** available on several platforms/RTOSes (you can find that on one of the experimental branches with a STM32L0 nucleo board).

**Comment by josesimoes** [comment]
Plus: we already have the concept of 'TARGET_SERIES' which is, correctly, non related with RTOS or anything else apart from the... SERIES of the target... 😄

**Comment by networkfusion** [comment]
When the ChibiOS 20x PR is merged, this current PR will contain even more conflicts. Given that most of the changes are simple renames, it would probably be easier to start again. This (closed) PR can be used as a reference.

**Pull request closed without merging**
