### PR TITLE
Increase reserved memory for ESP32 malloc

### PR DESCRIPTION
**Pull request by alberk8**
## Description
- Increase reserved memory for ESP32 malloc from 20k to 30k.
  
## Motivation and Context

- Fixes nanoFramework/Home#919.

## How Has This Been Tested?
- Run sample code without problem
- The extra 10kB is not enough to run any process that needs TLS/SSL.

[https://github.com/alberk8/nanoFramework-nordicspp](url)
## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by josesimoes — APPROVED** [review]
LGTM!

**Comment by josesimoes** [comment]
@alberk8 please clarify the above "The extra 10Kb is not enough to run any process that needs TLS/SSL"
Does this mean that with the extra 10k is NOT possible to run applications that use TLS?

**Comment by alberk8** [comment]
> @alberk8 please clarify the above "The extra 10Kb is not enough to run any process that needs TLS/SSL" Does this mean that with the extra 10k is NOT possible to run applications that use TLS?

Yes, the extra 10Kb is not enough to run TLS.  TLS alone needs between 22k to 27K,  It fluctuates and I cannot pin it down.

**Comment by alberk8** [comment]
> > Yes, the extra 10Kb is not enough to run TLS. TLS alone needs between 22k to 27K, It fluctuates and I cannot pin it down.
> 
> Any harm done on reserving upfront 60k?

Then we will not have enough left for nF to run app.   I think for the REV0 it is ok to run with TLS just that the user is aware of the limitation.  The only way to have BLE + WIFI + PSRAM is with REV3 hardware.

**Pull request merged**
