### PR TITLE
Update declaration for System.Net

### PR DESCRIPTION
**Pull request by CoryCharlton**
## Description
Updating signatures for IPAddress equality operators

## Motivation and Context
Required for https://github.com/nanoframework/System.Net/pull/310

## How Has This Been Tested?
On device

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [x] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [X] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by CoryCharlton** [comment]
This was a non-standard update of the stubs as some of it lives outside these files and methods that are not defined in the managed side exist. Care should be taken to ensure I didn't miss anything here.

**Review by josesimoes — APPROVED** [review]
LGTM

**Comment by josesimoes** [comment]
@CoryCharlton these are OK. The reason why all these have changed is that static fields are indexed in a single table for each assembly.

A couple of extra comments FYI and future PRs:
- a PR like this is "just" updating the declaration of the assembly. That's the name for it and no need to add the same comments as the originating PR. 
- It should be labeled as dependencies, as it's updating a dependency. Nothing new or no bug fix (that would be if something changed in the code). In doubt please take a look at the extra information inside parethesis in the check list of the PR template. 😉

**Comment by josesimoes** [comment]
@CoryCharlton can you please fix the conflicts so this can be merged?

**Comment by CoryCharlton** [comment]
This is NOT correct yet. DO NOT MERGE.

**Comment by CoryCharlton** [comment]
@josesimoes I believe this is good to go now.

**Comment by josesimoes** [comment]
@CoryCharlton I've just fixed the assembly version and checksum. These got lost in the process. 
Thanks for taking care of the conflcit.

**Pull request merged**
