### PR TITLE
Fixes infinite loop on bad pin value

### PR DESCRIPTION
**Pull request by dougboling**
## Description
If gpioPins->GetItem succeeds on the first call but fails later, 
gpioPinBundle will not be null and the loop never exits.
This fix adds an error check and sets gpioBinBundle to
NULL if detected.
"if (gpioPinBundle == NULL)" remains to catch any null 
blocks returned by GetItem.

Signed-off-by: Doug Boling <dbolinggh@bolingconsulting.com>

## How Has This Been Tested?
Tested by passing bad pin value to GpioController.Write
This results in an exception dump as expected.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nanoframework/nf-interpreter?pullRequest=2296) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nanoframework/nf-interpreter?pullRequest=2296) before we can accept your contribution.<br/><br/>:x: dougboling [sign now](https://cla.dotnetfoundation.org/nanoframework/nf-interpreter?pullRequest=2296)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nanoframework/nf-interpreter?pullRequest=2296) it.</sub>

**Review by josesimoes — APPROVED** [review]
LGTM! Thanks for the fix. Please sign the CLA so this can be merged.

**Comment by networkfusion** [comment]
@dougboling, are you able to sign the license agreement so this can be merged?

**Comment by dougboling** [comment]
I’m working on getting a release from my company. Sorry for the delay.

 

Doug

**Comment by josesimoes** [comment]
@dougboling no worries. Sorry for all the trouble. Hopefully you'll get that setup once and for all. For sure wouldn't want this to become a reason for you not to keep contributing to the project . 😉

**Comment by dougboling** [comment]
Thanks for the response. It’s for everyone’s good. If I posted w/o permission and they found out I’m not sure of the consequences. 

 

Big companies. I hadn’t worked directly for one for 25 years… until 3 years ago. Trying to re-learn obedience. It’s difficult.

 

Doug

**Comment by networkfusion** [comment]
> 

No worries from me... Working for a large (gov) org, I tend to keep my my development of OSS libs like nF seperate (and do it in my own time (from a personal capacity with a different GH username)). Generally though, large orgs "should" support things like this as "personal development" 😅 .

**Comment by josesimoes** [comment]
Hey @dougboling any update on this?

Be sure we don't want to make this painful to you. Much less discouraging you from making more contributions in the future! 

If you can't get that OK from your company I propose to make a on your behalf and credit you for the fix. Does that work better for you?

**Comment by dougboling** [comment]
Just got an email and a meeting is scheduled for tomorrow (5/31) to discuss with the open source committee. (The wheels move slowly here.) I should have an answer in the next day or so.

 

It’s a trivial change and if you want to update it on your own, I’m fine with that. Either way, we should be able to close this in the next few days.

 

Doug

**Comment by josesimoes** [comment]
@dougboling I'm afraid you've uncovered an issue in our documentation: I'm guess you're referring to the CLA that's on our documentation web site and not the CLA that you would sign when clicking the button above...

I'm fixing that now and apologies for any inconvenience.
Please click the CLA button above to read the CLA.

Also know that there is no separate CLA for corporations.

**Comment by dougboling** [comment]
Ok, good and bad. I was given permission to sign as an individual given there wasn’t a separate corporate agreement.

 

Now the bad, this is different text from what I had them review, so I’m going to have to send it to them. I don’t think there is anything substantively different in this text but I have to follow the rules. I hope they’ll get back quickly now that I have everyone involved. The one phrase:

 

“If You are signing this Agreement on behalf of Your employer, You represent and warrant that You have the necessary authority to bind the listed employer to the obligations contained in this Agreement.” 

 

May be an issue in that there was some discussion if we needed someone with corporate power of attorney to sign the doc instead of me. I hope I can get around that as they’re happy to give me permission to post the code. Arrgh.

 

Doug

**Comment by josesimoes** [comment]
@dougboling nothing to be sorry about! Really appreciate all your efforts to get through with this. Thank YOU! 😃

**Pull request merged**
