### PR TITLE
Fix descriptor events and add service UUID to advert

### PR DESCRIPTION
**Pull request by AdrianSoundy**
## Description

Events for descriptor read/write where not being fired.
Add the Service UUID to the Advertisement packet

## Motivation and Context
Problem reported on Discord by axa

## How Has This Been Tested?

Changes have been tested and now descritors are working correctly
Now when advertise a service it is found by a client ( Tested with Improv service )

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by AdrianSoundy** [comment]
Also requires changes to System.Device.Bluetooth

**Comment by AdrianSoundy** [comment]
@josesimoes  A lot of the code style issues came form the header file copied from the managed code output. Seems to be adding extra lines now.

**Review by josesimoes — APPROVED** [review]
LGTM! A lot of work into this. Thanks! 👍🏻

**Comment by josesimoes** [comment]
> @josesimoes A lot of the code style issues came from the header file copied from the managed code output. Seems to be adding extra lines now.

You mean on the subs header file with the declaration? Yes, that's been like that from the beginning. It was supposed to be improved with we add the code style check. I have it on my todo list but seems that I not getting there... 😅

**Pull request merged**
