### PR TITLE
Power shell script to autogenerate launch.json

### PR DESCRIPTION
**Pull request by networkfusion**
Please test on a number of machines before this script is integrated to iron out any edge cases.

### CODE REVIEW

**Comment by MikroBusNet** [comment]
Why is this PR not merged yet ? Are there any issues ?

**Comment by networkfusion** [comment]
none that I know of, but I want people to try it and give feedback (feel free)

**Comment by josesimoes** [comment]
@networkfusion there is no reason for this be hanging for so long... 😄 
Could you please move the changes in the debug instructions file to it's new location so this can be merged?

**Comment by josesimoes** [comment]
@networkfusion can we move this past the PR, please? ⏳ 
Just check if everything still makes sense and runs OK so this can be merged.

**Comment by josesimoes** [comment]
@networkfusion being you the owner of the oldest PR in the repo 🤣 
care to review this so it can be merged and we can close it? It's ruining the statistics man…

**Comment by networkfusion** [comment]
@josesimoes I am inclined to close this as it needs work to bring it up to date and no one seems to struggle with it too much. Also, ESP has a seperate template so things got more complicated...

**Comment by josesimoes** [comment]
I agree. Let's close it then.

It will remain here for reference if needed in the future.

**Pull request closed without merging**
