### PR TITLE
Graphics ready for merge

### PR DESCRIPTION
**Pull request by AdrianSoundy**
## Description
This PR is the initial Graphics branch updated so its ready for merge to develop branch

### Main changes
- Tidied up ESP32 CMakeLists.txt as no longer need to have separate library.
- Moved the Graphics memory init. and Graphics initialise to TargetHal.cpp ( Esp32 & STM32 discovery)
- Changed SPI display code to use platform agnostic SPI api
- Made SPI_to_Display.cpp use a passed config block so it can be used for any platform/setup, not just esp32 wrover
- Updated files to .Net foundation header
- Updated ESP32 cpu_spi.cpp  to have max transfer of 16K (This only defines how many DMA descriptors it uses)
- Changed to ESP32 Graphics_Memory.cpp to allocate a 16K graphics heap when not running on SPIRAM boards. This is to allow small displays to be used like (SSD1306).

azure-pipelines.yml
Currently only the ST_STM32F769I_DISCOVERY will include graphics by default.

Need to decide how to tackle ESP32. Automatic build doesn't include graphics.
Suggest we create a separate reference target for ESP32 for latest wrover boards. For anything else people will need to build own version.

Currently Touch interface is not complete and will be done once merged (@TerryFogg )

## How Has This Been Tested?

Targets were tested using Primitives sample application
- Wrover version 3 using ST7789V driver
- ESP32 with SPI - ILI93141 display
- ST_STM32F769I_DISCOVERY with inbuilt display - Otm8009a

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by josesimoes** [comment]
Finally went through this! Lots of code here. 😁

There is hardware specific code inside the "src" folder. For LCD and touch drivers.
The approach so far has been to have there only the code that's platform/RTOS agnostic. Everything else should be inside the platform specific folders. I really think we should keep that principle.

Also the JPEG and GIF library files are missing the proper copyright/license header.

If you prefer we can have this conversation in Discord...

**Comment by AdrianSoundy** [comment]
All the current code under src is platform agnostic. I did find a spurious header file that shouldn't have been there(Deleted).  

The GIF files have the proper copyright/license header.
The jpeg have a separate copyright header.

Not sure what that should be changed too, currently it like this:-


> /*
>  * jcapimin.c
>  *
>  * Copyright (C) 1994-1998, Thomas G. Lane.
>  * This file is part of the Independent JPEG Group's software.
>  * For conditions of distribution and use, see the accompanying README file.
>  *
>  * This file contains application interface code for the compression half
>  * of the JPEG library.  These are the "minimum" API routines that may be
>  * needed in either the normal full-compression case or the transcoding-only
>  * case.
>  *
>  * Most of the routines intended to be called directly by an application
>  * are in this file or in jcapistd.c.  But also see jcparam.c for
>  * parameter-setup helper routines, jcomapi.c for routines shared by
>  * compression and decompression, and jctrans.c for the transcoding case.
>  */
>

**Review by TerryFogg — APPROVED** [review]
Thanks for deleting spurious header. As for code in Src, I reasonably sure that I have separated the platform specific.

**Comment by josesimoes** [comment]
The correct header should be something like:

//
// Copyright (c) .NET Foundation and Contributors
// Original work Copyright (c) 1994-1998, Thomas G. Lane
// See LICENSE file in the project root for full license information.
//

**Comment by josesimoes** [comment]
On the hardware specific code I'm referring to:

src/nanoFramework.Graphics/Graphics/Displays/ST7789V_240x320_SPI.cpp src/nanoFramework.Graphics/Graphics/Displays/ST7789V_240x320_SPI.cpp
src/nanoFramework.Graphics/Graphics/Displays/Otm8009a_DSI_Video_Mode.cpp
src/nanoFramework.Graphics/Graphics/Displays/ILI9341_240x320_SPI.cpp 

src/nanoFramework.Graphics/TouchPanel/Devices/XPT2046.cpp 
src/nanoFramework.Graphics/TouchPanel/Devices/ft6x06_I2C.cpp

**Review by josesimoes — APPROVED** [review]
LGTM! Let's have this

**Pull request merged**
