### PR TITLE
Work on System.Convert

### PR DESCRIPTION
**Pull request by MikroBusNet**
Implementation of NativeToInt64 and NativeToDouble.

Signed-off-by: Christophe Gerbier <christophe@mikrobusnet.org>

### CODE REVIEW

**Comment by MikroBusNet** [comment]
Travis should be happy with ___clr_managed_heap_size__=0x2A000_ for F429iDiscovery.

**Comment by MikroBusNet** [comment]
José, when you have some time, could you please see the issue with the STM32F4_DISCOVERY board ?
I have changed the managed stack size and it has built fine locally. Since I do not have this board, I cannot really tell what is going on (both locally and with Travis).

**Comment by MikroBusNet** [comment]
What is happening with the ST_NUCLEO64_F091RC board and Travis ?
I did not change anything on this board ?!

**Comment by josesimoes** [comment]
@MikroBusNet it has run out of RAM... This is probably related with the Gpio being enabled. With the events added this has increased the required memory... But it sure looks a bit too much...
Please edit the Travis script and turn Gpio OFF

**Comment by MikroBusNet** [comment]
See PR #471

**Pull request merged**
