### PR TITLE
Adapted "add-i2s" to current main

### PR DESCRIPTION
**Pull request by BWalti**
## Description

- Took changes from "add-i2s" branch and re-built them on top of current main

EDIT: as per discussion I am now targeting the existing add-i2s branch and just update it with the "currently needed updates".

## Motivation and Context

- I would love to use I2S on ESP32 to play audio
- And as I do not completely understand what I am doing here (besides adapting code a bit here and there) I'd like to get feedback of what else I'd have to "adapt" to new guidelines / structures.

## How Has This Been Tested?

NO TESTING whatsoever has been done BESIDES building the firmware using the ESP32 dev container and flashing that one on to the ESP32. I actually don't understand in detail what I am doing :)

I assume that once the firmware is ready, one could build the managed proxy library to invoke corresponding native functionality - I am not sure if I may do this locally now, as I successfully flashed that image on one of my ESP32. I may give this a try tomorrow.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [x] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [x] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by josesimoes** [comment]
Hey @BWalti ! 😄 
Glad to see you're keen to have I2S working on ESP32. 

You should follow a different approach: as the working branch for I2S is `add-i2s` that's where the work has to be done.
Meaning that you should start your working branch (maybe `my-work-oni2s`) from `add-i2s` and submit your PRs against that branch here.

Build on the pipeline will happen as usual.
Local builds on dev container will work exactly the same way: it will build whatever is your active branch.

Hope I'm making sense... 🤪 

Anyway, feel free to discuss and engage in conversations on Discord. Suggest "development-class-libraries-general" channel.

**Comment by Ellerbach** [comment]
@BWalti great to see indeed the I2S work coming in :-) I recognize some of the code :-D I hope it will be easy to port back!

**Comment by BWalti** [comment]
> Hey @BWalti ! 😄 Glad to see you're keen to have I2S working on ESP32.
> 
> You should follow a different approach: as the working branch for I2S is `add-i2s` that's where the work has to be done. Meaning that you should start your working branch (maybe `my-work-oni2s`) from `add-i2s` and submit your PRs against that branch here.
> 
> Build on the pipeline will happen as usual. Local builds on dev container will work exactly the same way: it will build whatever is your active branch.
> 
> Hope I'm making sense... 🤪
> 
> Anyway, feel free to discuss and engage in conversations on Discord. Suggest "development-class-libraries-general" channel.

I fully understand - as @Ellerbach correctly recognized: it's all his work with just a few minor adaptions from my side - thus all kudos belong to him :)
I'll do this asap.

**Comment by BWalti** [comment]
This PR is now basically a merge main -> add-i2s + fixes.

I still have to test this out, therefore I am going to create a local managed wrapper around this to test it. (and maybe provide the managed wrapper in a new repo afterwards).

@josesimoes one point I am still unclear: as I most probably don't have access to the main repo - who is responsible for opening the PR from add-i2s to main in that repo at "the end"?

**Comment by josesimoes** [comment]
@BWalti when work on I2S branch is completed, one of the core team members will take care of PR against main branch.

For you to resume work on this, I strongly recommend that you perform a rebase from main, instead of a simple merge. That will make the commit history much cleaner and will also show only the changes in the add-i2s branch.
I can do that if you want.

**Comment by BWalti** [comment]
@josesimoes : Usually I'd prefer rebases to keep the history clean, but I checked the history of add-i2s and saw that there have already been some merges from ancient mains into add-i2s - and in my experience, if this happened at one point, a "rebase" on a newer main never actually works?

But I'd highly appreciate if you could fix this :) do I have to provide you with anything so that you are able to do this?

**Comment by josesimoes** [comment]
I can rebase our working branch. Just don't want to mess up with your changes on your fork. Plesee confirm. 🙂

**Comment by BWalti** [comment]
@josesimoes : you are free to go, thank you! :)

I have no changes outstanding right now, but found out yesterday evening, that I most probably will have a few todos:

- [ ] update the native bindings to match updated espressif I2S API
  I assume the implementation started against version [4.1](https://docs.espressif.com/projects/esp-idf/en/v4.1/api-reference/peripherals/i2s.html) because I see some keywords (e.g.: `channel_format`) in the native bindings which are not around in the [latest version](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/i2s.html) anymore
- [ ] find out how to build and test the managed wrapper locally (any way to disable the checksum check?)
- [ ] build the managed wrapper with a proper API (uh oh :) )
- [ ] put all the things together :)

**Pull request closed without merging**
