### PR TITLE
TinyPrintf replaced with nanoprintf, #693

### PR DESCRIPTION
**Pull request by SandorDobos**
According to nanoframework/home#693, TinyPrintf replaced with nanoprintf.

## Description
TinyPrintf removed, nanoprintf added.
sprintf not supported by nanoprintf, that's why sprintf() calls got replaced with snprintf() in codebase.
nanoprintf's float related code adjusted to doubles.
Added .Net conform rounding to precision-cut output, lie "G4".
The actual .Net compliance (not worse than with TinyPrintf) shown below.
The BADs are subjects of nanoframework/home#679.

 OK: (1234).ToString("D") expected: 1234
 OK: (-1234).ToString("D") expected: -1234
BAD: (1234).ToString("D6") expected: 001234 found: 1234  
BAD: (-1234).ToString("D6") expected: -001234 found: -1234 
 OK: (1234.567).ToString("F")) expected: 1234.57
 OK: (-1234.567).ToString("F")) expected: -1234.57
 OK: (1234).ToString("F1")) expected: 1234.0
 OK: (-1234).ToString("F1")) expected: -1234.0
 OK: (1234.56).ToString("F4")) expected: 1234.5600
 OK: (-1234.56).ToString("F4")) expected: -1234.5600
BAD: (123.456).ToString("G")) expected: 123.456 found: 123.456000
BAD: (-123.456).ToString("G")) expected: -123.456 found: -123.456000
BAD: (123.4546).ToString("G4")) expected: 123.5 found: 123.4546
BAD: (-123.4546).ToString("G4")) expected: -123.5 found: -123.4546
 OK: (1234.567).ToString("N")) expected: 1,234.57
 OK: (-1234.567).ToString("N")) expected: -1,234.57
 OK: (1234).ToString("N1")) expected: 1,234.0
 OK: (-1234).ToString("N1")) expected: -1,234.0
 OK: (1234.56).ToString("N3")) expected: 1,234.560
 OK: (-1234.56).ToString("N3")) expected: -1,234.560
 OK: (255).ToString("X")) expected: FF
BAD: ((Int32)(-1)).ToString("x")) expected: ffffffff found: FFFFFFFF
BAD: (255).ToString("x4")) expected: 00ff found: 00FF
 OK: ((Int32)(-1)).ToString("X4")) expected: FFFFFFFF

## Motivation and Context
- Fixes nanoframework/home#693

## How Has This Been Tested?
With code below.
```
    public class Program
    {
        public static void Main()
        {
            Debug.WriteLine("Hello from nanoFramework!");

            //AssertToConsole("(123.456).ToString(\"C\"))","",(123.456).ToString("C"));
            //AssertToConsole("(-123.456).ToString(\"C\"))","",(-123.456).ToString("C"));
            //AssertToConsole("(123.456).ToString(\"C3\"))","",(123.456).ToString("C3"));
            //AssertToConsole("(-123.456).ToString(\"C3\"))","",(-123.456).ToString("C3"));
            AssertToConsole("(1234).ToString(\"D\")", "1234", (1234).ToString("D"));
            AssertToConsole("(-1234).ToString(\"D\")", "-1234", (-1234).ToString("D"));
            AssertToConsole("(1234).ToString(\"D6\")", "001234", (1234).ToString("D6"));
            AssertToConsole("(-1234).ToString(\"D6\")", "-001234", (-1234).ToString("D6"));
            //AssertToConsole("(1052.0329112756).ToString(\"E\"))","",(1052.0329112756).ToString("E"));
            //AssertToConsole("(-1052.0329112756).ToString(\"E\"))","",(-1052.0329112756).ToString("E"));
            //AssertToConsole("(1052.0329112756).ToString(\"E2\"))","",(1052.0329112756).ToString("E2"));
            //AssertToConsole("(-1052.0329112756).ToString(\"E2\"))","",(-1052.0329112756).ToString("E2"));
            //AssertToConsole("(1052.0329112756).ToString(\"e\"))","",(1052.0329112756).ToString("e"));
            //AssertToConsole("(-1052.0329112756).ToString(\"e\"))","",(-1052.0329112756).ToString("e"));
            //AssertToConsole("(1052.0329112756).ToString(\"e2\"))","",(1052.0329112756).ToString("e2"));
            //AssertToConsole("(-1052.0329112756).ToString(\"e2\"))","",(-1052.0329112756).ToString("e2"));
            AssertToConsole("(1234.567).ToString(\"F\"))", "1234.57", (1234.567).ToString("F"));
            AssertToConsole("(-1234.567).ToString(\"F\"))", "-1234.57", (-1234.567).ToString("F"));
            AssertToConsole("(1234).ToString(\"F1\"))", "1234.0", (1234).ToString("F1"));
            AssertToConsole("(-1234).ToString(\"F1\"))", "-1234.0", (-1234).ToString("F1"));
            AssertToConsole("(1234.56).ToString(\"F4\"))", "1234.5600", (1234.56).ToString("F4"));
            AssertToConsole("(-1234.56).ToString(\"F4\"))", "-1234.5600", (-1234.56).ToString("F4"));
            AssertToConsole("(123.456).ToString(\"G\"))", "123.456", (123.456).ToString("G"));
            AssertToConsole("(-123.456).ToString(\"G\"))", "-123.456", (-123.456).ToString("G"));
            AssertToConsole("(123.4546).ToString(\"G4\"))", "123.5", (123.4546).ToString("G4"));
            AssertToConsole("(-123.4546).ToString(\"G4\"))", "-123.5", (-123.4546).ToString("G4"));
            AssertToConsole("(1234.567).ToString(\"N\"))", "1,234.57", (1234.567).ToString("N"));
            AssertToConsole("(-1234.567).ToString(\"N\"))", "-1,234.57", (-1234.567).ToString("N"));
            AssertToConsole("(1234).ToString(\"N1\"))", "1,234.0", (1234).ToString("N1"));
            AssertToConsole("(-1234).ToString(\"N1\"))", "-1,234.0", (-1234).ToString("N1"));
            AssertToConsole("(1234.56).ToString(\"N3\"))", "1,234.560", (1234.56).ToString("N3"));
            AssertToConsole("(-1234.56).ToString(\"N3\"))", "-1,234.560", (-1234.56).ToString("N3"));
            //AssertToConsole("(1).ToString(\"P\"))","",(1).ToString("P"));
            //AssertToConsole("(-0.39678).ToString(\"P\"))","",(-0.39678).ToString("P"));
            //AssertToConsole("(123456789.12345678).ToString(\"R\"))","",(123456789.12345678).ToString("R"));
            //AssertToConsole("(-123456789.12345678).ToString(\"R\"))","",(-123456789.12345678).ToString("R"));
            AssertToConsole("(255).ToString(\"X\"))", "FF", (255).ToString("X"));
            AssertToConsole("((Int32)(-1)).ToString(\"x\"))", "ffffffff", ((Int32)(-1)).ToString("x"));
            AssertToConsole("(255).ToString(\"x4\"))", "00ff", (255).ToString("x4"));
            AssertToConsole("((Int32)(-1)).ToString(\"X4\"))", "FFFFFFFF", ((Int32)(-1)).ToString("X4"));

            Debug.WriteLine("--------------------");
        }


        private static void AssertToConsole(string lbl, string expected, string str)
        {
            if (str != expected)
            {
                Debug.WriteLine($"BAD: {lbl} expected: {expected} found: {str}");
            }
            else
            {
                Debug.WriteLine($" OK: {lbl} expected: {expected}");
            }
        }
}
```

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Dependencies (update dependencies and changes associated, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by josesimoes — APPROVED** [review]
LGTM! Thanks.

**Comment by josesimoes** [comment]
This is a nice 1st step towards improving/fixing this.

**Comment by charlesnicholson** [comment]
Hey everyone- I'm the original nanoprintf author; it's very cool to see that it's useful! I'm just leaving a note to suggest upgrading; the latest version is much smaller, fixes a bunch of bugs, has binary-printing support, and has some snprintf-related safety features that you might enjoy.

It's still hosted over here if you're interested: https://github.com/charlesnicholson/nanoprintf

**Comment by josesimoes** [comment]
Hey @charlesnicholson. Thanks for reaching out! 😃  nanoprintf it's very usefull to us, appreciate all the work you've done with it.
Also, of course, for the heads up on the new version. We'll sure update the code. 👍🏻

**Pull request merged**
