### PR TITLE
Fix computation of GC reachability for arrays with referenced objects

### PR DESCRIPTION
**Pull request by josesimoes**
## Description
- Add code to process array elements for referenced elements.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by kskowronsk** [comment]
Now the algorytm does not dig into arrays and does not mark alive objects referenced by the array. As it may be the only reference to some objects it would cause these objects to be invalidly freed

**Comment by josesimoes** [comment]
@kskowronsk can you please elaborate? This was tested against the GCStress test app and it run for 30 minutes without any OOM exception nor hard faults.

**Comment by MateuszKlatecki** [comment]
I can confirm that changes from this PR as well from this PR https://github.com/nanoframework/nf-interpreter/pull/2706 introduce another problems. Our system is unable to even boot after making these changes.

please try run this program and check what is inside array after for loop. 

```cs
public class Program
{
    public static void Main()
    {
        const int max_array_size = 786432 - 68; //786364
        object[] arrays = new object[1047];

        for (int i = 0; i < arrays.Length; i++)
        {
            var n = max_array_size / 256;
            arrays[i] = new object[n];

            for (int j = 0; j < n; j++)
            {
                (arrays[i] as object[])[j] = new byte[2];
            }
        }
        Thread.Sleep(Timeout.Infinite);
    }
}
```

I would expect our device to run out of memory (8MB of RAM) during the loop execution. After these fixes, the program comes to an end, but in the table there is:
image

**Comment by kskowronsk** [comment]
The above behavior is expected for this fix as GC releases objects that are referenced by an array. 
Before this fix the array's elements were put onto the mark stack and processed later recursively.
After the fix all elements are marked in place and there is no recursion. The reachability graph ceased to "reach" into the arrays subelements so any referenced objects are not marked by GC anymore.

**Comment by josesimoes** [comment]
Understood and yes, that is correct. Working on a fix.

**Pull request merged**
