### PR TITLE
Rework github actions so devcontainer images aren't published on forks

### PR DESCRIPTION
**Pull request by networkfusion**
## Description

* Dont publish docker container on forks (by default).
* Update more action versions.

## Motivation and Context

* Found more actions that were out of date.
* Docker image would try to push on forks, which will likely fail.

## How Has This Been Tested?

Requires proof of working, but "seems" correct given other repos I have used the concept on.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by josesimoes** [comment]
Don't think this should be enforced from upstream... developers may want to publish containers. GtiHub actions can be disabled per repository, so I don't think this is needed.
I have a fork of this repo on Eclo gtihub account and other customers and this was never an issue. 🤔

**Comment by networkfusion** [comment]
My take on this is that by default, if you fork the repo, if you sync the `main` branch (to keep it up-to-date) and the dev container has changed, you will get docker images for it published to your fork. For most developers, it is unlikely you want that to happen.

I guess this to a point goes in-line with my CI concept that uses the dev-containers CI that I have developed and can (with a few minor adjustments) publish a rolling release...

But perhaps needs a little more thought.

**Comment by josesimoes** [comment]
Just updated (from github web interface) Eclo fork.
This is what I got on the actions run:

image


Current Actions config on the repo:

image

**Comment by josesimoes** [comment]
But I see your point. 

To me if the default should be off (which I agree it should) then the change here should be turn it OFF by default so it wont run. Not dependent on the branch or repo owner.

The validation to run (or not) could be a repo variable. This way one doesn't have to change the action yaml. Just needs to add _that_  variable that allows the action to run.

**Comment by networkfusion** [comment]
Interesting... This is what I was fighting: https://github.com/networkfusion/nf-interpreter/actions/runs/6076031595

I will split this PR out for the moment.

**Comment by networkfusion** [comment]
I dont want to be the owner of this (since it could cause undesirable effects if I have something wrong), but something like:

```
# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

name: Build Dev Container for all platforms

env:
  GCR_IMAGE: ghcr.io/nanoframework/dev-container-all
  GCR_FILE: .devcontainer/sources/Dockerfile.All
  PUBLISH_IMAGE: false

on:
  push:
    paths:
      - '**Dockerfile.All'
    
  workflow_dispatch:

jobs:
  build:
    if: ${{ (github.repository_owner == 'nanoframework' && github.ref == 'refs/heads/main') || env.PUBLISH_IMAGE) }}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get container version
      run: |
        $dockerfileContent = Get-Content(".devcontainer/Dockerfile.All")
        $dockerfileContent -match '(?<=\:)(?:[v]\d+.\d+)'
        $containerVersion = $Matches[0].ToString()
        echo "GCR_VERSION=$containerVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CONTAINER_BUILD_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        file: ${{ env.GCR_FILE }}
        push: true # Will only build if this is not here
        tags: |
          ${{ env.GCR_IMAGE }}:${{ env.GCR_VERSION }}
          ${{ env.GCR_IMAGE }}:latest

```

for `devcontainer-all.yaml`

**Comment by josesimoes** [comment]
I'm OK with the above except for the part that it is locking this to the nanoframework repository. 
I really don't think we have to enforce this. Otherwise the env var is not even required, only for our repo.

It should be:
`if: ${{ (github.ref == 'refs/heads/main') && env.PUBLISH_IMAGE) }}` 

so it builds only on merge to main AND if the respective env var is set on the repository.

**Comment by networkfusion** [comment]
So, this would be my latest attempt: would be to add: `  PUBLISH_IMAGE: 'never' # change to 'true' to publish.` to the environment variables and change it to `push: ${{ env.PUBLISH_IMAGE }} # Will only publish image if required.`

But I am not sure if that will work, since not sure if the `env.PUBLISH_IMAGE` would be picked up from the repo or not.

I can push the changes though...

**Comment by josesimoes** [comment]
The condition check should be on the be on the `build` not on `push`. I mean it doesn't make any sense to go and build the damn thing if is not going to be used anywhere, right?

As for the `env.PUBLISH_IMAGE` it suffices to have defined or not, doesn't matter the content.
Scope wise: it can be repo or org, irrelevant.

**Comment by josesimoes** [comment]
@networkfusion I've just added `PUBLISH_IMAGE` as repo var here.

**Comment by networkfusion** [comment]
Not sure...

currently the build only happens if the source is changed e.g. 
image

It is good to check that even when the image is not deployed (to make sure there are no issues with the changes).

But I see your point...

**Comment by josesimoes** [comment]
Separation of concerns: if I don't have that var define => I don't care about docker images, no need to build anything. Plus that will be fired (for nothing again) whenever there is a change on those files from upstream on merge. 🤷🏻‍♂️

**Comment by networkfusion** [comment]
Ok, changed to a build condition and made the env var a bool.

**Comment by Ellerbach** [comment]
> What should be on the yaml it's a verbose comment explaining this. Something like "Hey, if you want to enable dev container to build and be pushed to your repo, you have to add a PUBLISH_IMAGE variable to the repository."
Feel free to adjust, of course. 😁

And please document that somewhere easy to find :-) Because in 6months, I'm not sure we will remember :-D And also for the people who fork, so they can do it as well on their own fork! Thanks

**Comment by networkfusion** [comment]
How about:
```
# NOTE: TO ENABLE THIS JOB
# add it to your repo "Repository Variables"
# See: https://docs.github.com/en/actions/learn-github-actions/variables#creating-configuration-variables-for-an-environment
# OR uncomment the following line: 
  # PUBLISH_IMAGE: true # change to 'true' to build and publish.

```

**Comment by josesimoes** [comment]
@networkfusion OK with the explanation.

You won't mind me insisting on this... 😅  Not OK with the var being in the yaml. 
Configuring the pipeline behaviour by tweaking the yaml file is completely off on the approach followed in this project.
You can see this on all pipelines, PS1, etc. Whenever there is anything configurable it ALWAYS outside the yaml or scripts. It's a variable that you set somewhere, it's a configuration on the pipeline tool, it's a template file that you can adjust at will and DOES NOT clash with the version control. So please let's keep this good practice here, OK? 😁

**Comment by networkfusion** [comment]
Okay, hopefully the latest push is more suitable.

**Comment by networkfusion** [comment]
Note: just checked on my own fork and does not currently work 😒 

image

**Comment by josesimoes** [comment]
@networkfusion please pull and give another spin

**Comment by networkfusion** [comment]
No, still fails (at least on forks). Technically as far as I can tell is the right solution being `${{ github.env.PUBLISH_IMAGE }}` but that still does not take into account the default on a fork not having the variable that exists, so we somehow need to also check for that?!

**Comment by josesimoes** [comment]
@networkfusion the context to access this is `vars` not `github.env` so I've fixed the fix. If you care to give one last try... if not, let's just forget about this and move along.

**Comment by networkfusion** [comment]
> @networkfusion the context to access this is `vars` not `github.env` so I've fixed the fix. If you care to give one last try... if not, let's just forget about this and move along.

Right. I already had that in my fork, but I screwed up the repo variable (corrected the source).

The build is now attempted as expected, but the next thing is:
image
Although likely due to the Action updates, so probably for another PR.

For testing, my action was https://github.com/networkfusion/nf-interpreter/actions/runs/6100213120/job/16554366410 which commented out:
```
    branches:
      - main
    paths:
      - '**Dockerfile.All'
```
to force the build.

**Comment by networkfusion** [comment]
Actually, I have just noticed that the docker image should not be pushing to the `nanoframework` repo 😱

**Comment by networkfusion** [comment]
So... perhaps the files should be like:
```
# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

name: Build Dev Container for all platforms

env:
  GCR_IMAGE: dev-container-all
  GCR_FILE: .devcontainer/sources/Dockerfile.All

on:
  push:
    # branches:
    #   - main
    # paths:
    #   - '**Dockerfile.All'
    
  workflow_dispatch:

jobs:
  build:
    if: ${{ vars.PUBLISH_DOCKER_IMAGE == 'true' }}
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Get container version
      run: |
        $dockerfileContent = Get-Content(".devcontainer/Dockerfile.All")
        $dockerfileContent -match '(?<=\:)(?:[v]\d+.\d+)'
        $containerVersion = $Matches[0].ToString()
        echo "GCR_VERSION=$containerVersion" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        file: ${{ env.GCR_FILE }}
        push: true # Will only build if this is not here.
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ env.GCR_IMAGE }}:${{ env.GCR_VERSION }}
          ghcr.io/${{ github.repository_owner }}/${{ env.GCR_IMAGE }}:latest
```

**Comment by josesimoes** [comment]
Setting the output repository it's outside the scope of this PR and what we're trying to acomplish.
If the developer is looking into publishing the dev containers to it's own repo, it's because it's changing something fundamental from what we have and it will be on a different yaml file, etc.

Please let's keep the focus: we're trying to solve the problem of NOT building the dev containers on forks. I believe this is done, so let's wrap up this PR. 😅

**Pull request merged**
