### PR TITLE
Fix depleting lwip socket pool

### PR DESCRIPTION
**Pull request by alberk8**
## Description

- Add done_socket(sock) to lwip_socket_get_err()
- Add done_socket(socket) to lwip_connect where err == ERR_INPROGRESS
- Fix valid for ESP32 and ChibiOS platforms. NXP needs to be addressed separatly.

## Motivation and Context

- Opening and Closing socket does not deplete socket pool
- Once connecting to socket will result in socket being held indefinitely,  Closing socket at this point does release it to the pool.
- Fixes nanoframework/Home#900. 

## How Has This Been Tested?

Test project: https://github.com/alberk8/nanoFramework-HttpWebRequest
- Tested on ESP32-WROOM and ESP32-WROVER.
- Tested on ST_STM32F769I_DISCOVERY (@josesimoes)

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by josesimoes — APPROVED** [review]
LGTM! Congrats on another great fix for network! :+1:

I'll just give it a try on a STM32 target before merging.

**Comment by josesimoes** [comment]
Seems that the fix for NXP might not be the appropriate one... Investigating.

**Comment by josesimoes** [comment]
When comparing "our" implementation of lwIP sockets for NXP platform, I found out that it seems to be quite outdated from the upstream source file! 
I have reverted your proposed fix and I'm pinging @nanoframework/nxp-developers to perform a close check on this. 
It seems that the sockets implementation need to be brought to speed with the official code... Anyone over there care to do it? 😉

**Comment by networkfusion** [comment]
Would it be appropriate to merge this one and raise an issue (with link to this PR) for NXP targets?

**Comment by josesimoes** [comment]
> Would it be appropriate to merge this one and raise an issue (with link to this PR) for NXP targets?

I'm still to test this with STM32

**Comment by josesimoes** [comment]
Tested successfully on ST_STM32F769I_DISCOVERY.

**Pull request merged**
