### PR TITLE
Upgrade ESP32 IDF to v5.2.2

### PR DESCRIPTION
**Pull request by AdrianSoundy**
## Description
- Minor changes to update IDF form v5.1.4 to v5.2.2
  + Uart defines changed to enum so serialport needed to be updated
  + Other typing issues
- Bump dev containers versions.
- Bump version to 1.12.0
- Reset revision counters for targets.

## Motivation and Context

Needed to be done.

## How Has This Been Tested?

Run builds on Esp32, ESp32_S3, ESp32_C6

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [x] Dependencies/declarations (update dependencies or assembly declarations and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

## Summary by CodeRabbit

- **New Features**
	- Upgraded the ESP-IDF version from 5.1.4 to 5.2.2 across various components, enhancing functionality and compatibility.
	- Improved caching mechanism for ESP32 tools in Azure Pipelines, ensuring the use of the latest version.

- **Bug Fixes**
	- Enhanced type safety and configuration handling in the UART and interrupt systems for improved reliability.

- **Chores**
	- Updated version numbers in configuration files to reflect the new release version (1.12.0).

### CODE REVIEW

**Comment by AdrianSoundy** [comment]
@josesimoes 
Not sure if I got all the dev container changes required

**Review by josesimoes — APPROVED** [review]
LGTM!
I've just bumped the dev containers versions and the components cache. All the rest was OK.

**Comment by AdrianSoundy** [comment]
@josesimoes 
Thanks for completing this overnight :-)

**Comment by josesimoes** [comment]
@AdrianSoundy no problem! Thank YOU for making it happen. 😄

**Pull request merged**
