### PR TITLE
Add implementation for platform_heap realloc

### PR DESCRIPTION
**Pull request by networkfusion**
## Description
Fix the implementation of realloc for ChibiOS platform targets

## Motivation and Context
Although it is not used anywhere, it was implemented incorrectly and did not align with the implementation of other platforms.

## How Has This Been Tested?
Built locally against an STM32F769i in debug mode.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Review by josesimoes — APPROVED** [review]
LGTM! Nice catch

**Comment by networkfusion** [comment]
Interesting...
image

**Comment by josesimoes** [comment]
@networkfusion seems that our mcuconf.h files are waaaay outdated... 😯 
That define is supposed to be there.

We should update those on a separate PR. 
Any chance you can tackle that?

**Comment by networkfusion** [comment]
Requires https://github.com/nanoframework/nf-interpreter/pull/2624 before this can complete.

**Pull request merged**
