### PR TITLE
Improve Storage part 2

### PR DESCRIPTION
**Pull request by networkfusion**
## Description

* Align names for drive defines.
* Take into account all drives when enumerating.
* Improve checks to only need a single char for drive letter.
* Rename the nanoHal header to move away from "Windows" naming.
* Remove a duplicate include.

Each change is kept seperate incase of individual merge.

## Motivation and Context

Code Maintainability.

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Review by josesimoes — COMMENTED** [review]
I have no problem with the rename to move away from Windows to Persistent.
Now about the defines for the drives name: that's another story.
These were using Index0...1 etc on purpose as those are the order they show when enumerated by FATFS.

Hard coding this to (for example) `USB_DRIVE_LETTER` is assuming that there will be an USB MSD on the system and that it will be at INDEX 1, which may not be the case. There can be an SD Card drive at INDEX 0. Or not... 

Any renaming seen necessary here should follow an agnostic naming pattern.

**Comment by networkfusion** [comment]
> I have no problem with the rename to move away from Windows to Persistent. Now about the defines for the drives name: that's another story. These were using Index0...1 etc on purpose as those are the order they show when enumerated by FATFS.
> 
> Hard coding this to (for example) `USB_DRIVE_LETTER` is assuming that there will be an USB MSD on the system and that it will be at INDEX 1, which may not be the case. There can be an SD Card drive at INDEX 0. Or not...
> 
> Any renaming seen necessary here should follow an agnostic naming pattern.

My concept towards inprovements here are this:
We are not Windows and cannot expect a user to enumerate an environment, so the filesystem should always be constent.
FatFS does not expect an enumeration, and we are probably fighting against it.
The naming was inconsistent, We should choose one or the other.

Personally (as a developer) I (think) I would prefer a (say) 3 letter drive name that relates to the drive (like linux) rather than a 1 letter name that is based on DOS. I note that this needs us to deprecate (rather than remove).

But, would add that some of the changes in this PR are helpful and optimize code. Just need split them.

**Comment by networkfusion** [comment]
@josesimoes hopefully the changes should go some way towards your comments. Let me know what else.

**Comment by networkfusion** [comment]
Unfortunatly, I missed the fact that `DRIVE_LETTER_LENGTH` is used extensively with windows storage... so probably back to the drawing board.

**Comment by networkfusion** [comment]
Closing as obsolete. A new PR can be created later if needed.

**Pull request closed without merging**
