### PR TITLE
Improve devcontainer.json

### PR DESCRIPTION
**Pull request by networkfusion**
## Description

Improve devcontainer.json to align schema with what is expected.
It also improves the spelling and grammar.

## Motivation and Context

The devcontainer schema has changed since the initial version was commited.
The spelling and descriptions needed improvement.

## How Has This Been Tested?

This was tested in the CI, but not a local instance.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by networkfusion** [comment]
@Ellerbach , if possible, please check that this works in a local environment.

Also, is there any real need for the line `"source=${env:HOME}${env:USERPROFILE}/.azure,target=/home/vscode/.azure,type=bind"` to be enabled by default, as it breaks in a CI environment...

**Review by Ellerbach — APPROVED** [review]
Looks good to me. And yes, the format has evolved since this has been created.
Also, it's now possible to have multiple dev containers. We may look at this and adjust as well.
In short, you can create directories with this same json and adjust the dockerfile or anything else.

**Comment by Ellerbach** [comment]
> Also, is there any real need for the line `"source=${env:HOME}${env:USERPROFILE}/.azure,target=/home/vscode/.azure,type=bind"` to be enabled by default, as it breaks in a CI environment...

And that's ont needed, just if the Azure tools are installed

**Comment by networkfusion** [comment]
Ok, I have commented out the azure cli (by default). Am I ok to merge?

**Comment by Ellerbach** [comment]
> Am I ok to merge?

Sure :-) And you did :-)

**Pull request merged**
