### PR TITLE
Fix unlinking allocated GPIOs.

### PR DESCRIPTION
**Pull request by martin-kuhn**
## Description
Enabling chibiOS debug checks showed some error during unlinking of allocated GPIOs. The method UnlinkInputState() disables the LineEvent, performs the Unlink and frees the gpio_input_state pointer. Hence we can not use this pointer in the following statement but we have to use  gpioInputList.FirstNode() instead.

## How Has This Been Tested?
This has been tested on a custom STM32F427 based MCU board.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: Martin Kuhn martin.kuhn@csa.ch

### CODE REVIEW

**Comment by josesimoes** [comment]
@martin-kuhn can we move forward with the code review? 😃

**Comment by martin-kuhn** [comment]
@josesimoes Sorry for the delay.
In my tests, this works fine. Since we do the unlinking of the gpios in a while loop with the condition that the next element can not be null, there will be one gpio left after the last iteration that won't be unlinked. Hence the gpioInputList.FirstNode() can never be null, right?

**Comment by josesimoes** [comment]
Yes, but you can only call `Next()` on an existing element.
With this code on the "last" iteration you'll get a pointer to the "fist" one, which is the last.
When the execution reaches the condition and calls `Next()` it won't execute because there is no next there is only one. Meaning that the last element will remain there.

**Comment by martin-kuhn** [comment]
Yes, this is exactly what I mean. But this would also be the case if we would switch to your suggestion, wouldn't it? As long as the condition of the while loop is pGpio->Next() != NULL, there will always be one remaining.

**Comment by josesimoes** [comment]
So let’s have it changed then so there is none left. OK?

**Comment by martin-kuhn** [comment]
what about this?

**Comment by josesimoes** [comment]
@mbern could you please sign the CLA so this PR can be merged? Thank you!

**Pull request merged**
