### PR TITLE
Ignore CMake files

### PR DESCRIPTION
**Pull request by cw2**
Signed-off-by: Stanislav Šimíček <cw2@users.noreply.github.com>

### CODE REVIEW

**Comment by cw2** [comment]
Sorry, I don't understand. CMakeCache.txt and CMakeFiles folder are generated during build, they are intermediate artifacts that cannot be included in repository. They has to be added to .gitignore, so they do not appear in the commit made in otherwise unmodified branch:

Current behavior:
1. In fresh master, `git commit` -> no changes detected
2. build STM32F4 discovery image
3. `git commit` -> CMakeCache.txt and CMakeFiles folder detected for addition

Correct/wanted behavior:
1. In fresh master, `git commit` -> no changes detected
2. build STM32F4 Discovery image
3. `git commit` -> **no changes detected**

**Comment by cw2** [comment]
The build was run from <repo>\build\ directory.

**Comment by josesimoes** [comment]
> CMakeCache.txt and CMakeFiles folder are generated during build

That is correct. Both CMakeCache.txt and CMakeFiles folder have to show up inside the build folder (which is already ignored) so there should be no need for a particular ignore for those. Could you please check if this is what you are seeing in your setup?

> The build was run from <repo>\build\ directory; following the second example instructions.

That should make all the build artefacts to go into the build folder... Are you using the full command line up to the double dots `..` at the end?

**Comment by cw2** [comment]
It had to be a problem with one of my previous builds - after using fresh repos, CMake files are generated only in build directory.

**Comment by josesimoes** [comment]
Glad to know that. 
I've found that when something is behaving strange with the build and it was working just before that wiping the build folder and start over is usually all that it takes.

**Comment by cw2** [comment]
Those files were generated in \targets\CMSIS-OS\ChibiOS\ST_STM32F4_DISCOVERY directory, so wiping build did not help (I do that almost always, just to be sure).

**Comment by cw2** [comment]
I probably run cmake from there once...

**Pull request closed without merging**
