### PR TITLE
Align FatFS code page with ESP32

### PR DESCRIPTION
**Pull request by networkfusion**
## Description

The Code Page used by FatFS was not consistant across platforms.

## Motivation and Context

Code page `850` might be handled incorrectly.
Although the `workingBuffer` allows for it, the `stringBuffer` does not.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Review by josesimoes — COMMENTED** [review]
According to wikipedia, 437 is the old legacy IBM DOS page... despite it could be the default for ESP23, we can easily override that using the corresponding config option for system.config or our own fatfs config.
Using 850 seems like a broader code page....

**Comment by networkfusion** [comment]
> .

I agree. But as the ESP32 is more widely used (tested), was thinking that we should at least align with it, and then update the config if required.

**Comment by networkfusion** [comment]
Additional: formatting devices with the FAT file system seems to default to `437` (I guess for backwards compatibility).

**Comment by networkfusion** [comment]
Extra: http://elm-chan.org/fsw/ff/doc/appnote.html 
image

**Comment by josesimoes** [comment]
Interesting all that reading! Nice finding.
Considering all the above and that we're supporting UTF-8, I would say that we should update our FF config to:

FF_CODE_PAGE 437 (recomended to decrease code size, especially when enabling Unicode)
FF_USE_LFN 3 (already there)
FF_LFN_UNICODE 2 (currently 0, this will make it support UTF-8)
FF_LFN_BUF 765 (to support UTF-8)
FF_SFN_BUF 34 (to support UTF-8)

**Comment by josesimoes** [comment]
Just added the changes discussed above. Tested with ORGPAL3 and ORGPALX.

**Review by josesimoes — APPROVED** [review]
LGTM!

**Comment by josesimoes** [comment]
Reverting the UTF-8 changes as these affect also ESP32. Should be added in another PR.

**Pull request merged**
