### PR TITLE
Update win_dev_gpio_native_Windows_Devices_Gpio_GpioPin.cpp

### PR DESCRIPTION
**Pull request by MikroBusNet**
## Description
Single XOR operation more efficient than if/then tests.

## Types of changes
- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by MikroBusNet** [comment]
"^" is not the XOR operator in C ?

**Comment by josesimoes** [comment]
> "^" is not the XOR operator in C ?


It is. It's just that the C/C++ compiler is not as "smart" as the C# one... It's not able to perform the logic operation among different types.

**Comment by MikroBusNet** [comment]
So it can be solved by casting the values.

**Comment by josesimoes** [comment]
Didn't try that as it looked too messy...

Anyways I was having a hard time debugging that piece of code and needed to see the values in the vars. That's why ended up as it is now.

**Pull request merged**
