### PR TITLE
Enable Lwip feature - DONT MERGE YET

### PR DESCRIPTION
**Pull request by networkfusion**
This will allow networking to be added to boards.

Feedback requested on all changes.

Testing required...

### CODE REVIEW

**Comment by networkfusion** [comment]
Also I am not sure why TRAVIS is failing, the STM32F769I (at least) is building successfully locally

**Comment by josesimoes** [comment]
@networkfusion check the build log in the various builds:

https://travis-ci.org/nanoframework/nf-interpreter/builds/268087510?utm_source=github_status&utm_medium=notification

(can reach this too by clicking details below at the check list)

**Comment by networkfusion** [comment]
yes, I have looked, the error doesn't make sense to me (since it is working locally)

**Comment by networkfusion** [comment]
#define HAL_USE_MAC currently needs to be set inside halconf. I am sure this is being done in a better way by I2C etc but I have no idea how... pointers welcome...

**Comment by josesimoes** [comment]
Starts in the main CMake goes to target_platform.h.in and you need to comment the current define in hal_config.

Follow the option name and you'll find your way through it

**Comment by networkfusion** [comment]
so basically all I have to do is add:
set(HAL_USE_MAC_OPTION TRUE CACHE INTERNAL "HAL MAC for NF_FEATURE_USE_NETWORKING")

and comment out HAL_USE_MAC in all the halconf files?

**Comment by josesimoes** [comment]
Yeap! Simple isn't it?! 😉

**Pull request merged**
