### PR TITLE
Update FatFs to R0.15

### PR DESCRIPTION
**Pull request by networkfusion**
## Description

This PR updates FatFs to R0.15. for ChibiOS and NXP targets (ESP32 use their own version).
Given it has breaking changes compared to R0.14b, it was necessary to move to our own version of `fatfs_syscall.c` which may be useful anyway as it allows us to use  `platform_malloc` and `platform_free`  which is the prefered option.

## Motivation and Context

Multiple issues which we use are fixed.
Improvements include:
```
R0.15 (November 6, 2022)
  Changed user provided synchronization functions in order to completely eliminate the platform dependency from FatFs code.
  FF_SYNC_t is removed from the configuration options.
  Fixed a potential error in f_mount when FF_FS_REENTRANT.
  Fixed file lock control FF_FS_LOCK is not mutal excluded when FF_FS_REENTRANT && FF_VOLUMES > 1 is true.
  Fixed f_mkfs() creates broken exFAT volume when the size of volume is >= 2^32 sectors.
  Fixed string functions cannot write the unicode characters not in BMP when FF_LFN_UNICODE == 2 (UTF-8).
  Fixed a compatibility issue in identification of GPT header.
```
NOTE: Community targets still need updating.

## How Has This Been Tested?

I need help to sanity check the changes required in  `fatfs_syscall.c` for all targets.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [x] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by networkfusion** [comment]
@josesimoes , I am not sure on the appertite for this (yet), but if there is, could you have a look. I am particularly worried that it wont work with `semaphores` since it should be using `mutexs`. Also whether we should now be using "platform" memory functions.

**Comment by josesimoes** [comment]
@networkfusion nothing against that. Although I still haven't check the code. 😅 
I can see you're still working on it. Please ping me when it's OK to review.

**Comment by networkfusion** [comment]
> @networkfusion nothing against that. Although I still haven't check the code. 😅 I can see you're still working on it. Please ping me when it's OK to review.

Can you advise me on whether I should be putting efforts into making it a mutex or reverting to semaphores for this? I realize that they are kinda similar, but having trouble either way I try (and do not really understand them or ChibiOS enough) 😓

**Comment by networkfusion** [comment]
Wow, it built the orgpal3, so lets see if all are now clear!

**Comment by networkfusion** [comment]
As a (justified) note, Storage is already broken on at least the STM32F769I running the last `main` firmware.

Sample program to prove is:

using System;
using System.Diagnostics;
using System.IO;
using System.Text;
using System.Threading;

namespace BasicFileSystemExample
{
    public class Program
    {

        public static void Main()
        {
            #region Variables

            //string sampleFilePath = "D:\\sampleFile.txt";
            //string sampleFilePath2 = "D:\\sampleFile2.txt";
            //string sampleFilePath3 = "D:\\test.txt";
            //string sampleText = "Lorem Ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. ";

            #endregion


            #region Init

            // Init
            // Wait until the Storage Devices are mounted (SD Card & USB). 
            // This usally takes some seconds after startup.
            // Not required for Internal drive or drives mounted from managed code. See mount sample.
            Thread.Sleep(3000);     
            
            // D: is SD Card
            // E: is USB drive
            // I: is Internal flash drive

            #endregion

            Debug.WriteLine("+++++ System.IO.FileSystem examples +++++");

            //Debug.WriteLine(CheckStorageDevices());

            var dirs = Directory.GetDirectories("D:\\");
            foreach (var dir in dirs)
            {
                Debug.WriteLine($"Found folder: {dir}");
            }

            //Debug.WriteLine("+++++ Creating a sample file +++++");
            //File.Create(sampleFilePath);

            //byte[] sampleBuffer = Encoding.UTF8.GetBytes(sampleText);

            //FileStream fs = new FileStream(sampleFilePath, FileMode.Open, FileAccess.ReadWrite);
            //fs.Write(sampleBuffer, 0, sampleBuffer.Length);
            //fs.Close();


            //if(fs.CanSeek)
            //{
            //    Debug.WriteLine("+++++ Modify sample file +++++");
            //    // Seek to beginning of the file and write something there
            //    fs.Seek(0, SeekOrigin.Begin);
            //    string startText = "This is the start./r/n";
            //    fs.Write(Encoding.UTF8.GetBytes(startText), 0, startText.Length);

            //    // Go to the end of file and write something there
            //    fs.Seek(0, SeekOrigin.End);
            //    string endText = "/n/nThis is the End.";
            //    fs.Write(Encoding.UTF8.GetBytes(endText), 0, endText.Length);
            //}

            //fs.Dispose();
            //Debug.WriteLine("+++++ Copy a file to USB drive +++++");
            //File.Copy(sampleFilePath, sampleFilePath2);

            //Debug.WriteLine("+++++ Move File Back to SD card +++++");
            //File.Move(sampleFilePath, "D:\\sampleFileMove.txt");

            //Debug.WriteLine("+++++ Change file attributes +++++");
            //File.SetAttributes(sampleFilePath2, FileAttributes.ReadOnly);

            //Debug.WriteLine("+++++ Read text from file +++++");
            //FileStream fs2 = new FileStream(sampleFilePath2, FileMode.Open, FileAccess.Read);
            //byte[] fileContent = new byte[fs2.Length];
            //fs2.Read(fileContent, 0, (int)fs2.Length);
            //fs2.Close();

            //Debug.WriteLine("+++++ Read text from unmodded file +++++");
            //FileStream fs3 = new FileStream(sampleFilePath3, FileMode.Open, FileAccess.Read);
            //byte[] fileContent = new byte[fs3.Length];
            //fs3.Read(fileContent, 0, (int)fs3.Length);
            //fs3.Close();

            Debug.WriteLine("+++++ System.IO.FileSystem examples end +++++");
        }
    }
}

**Comment by networkfusion** [comment]
Discarding the fact that DMA cache issue are really causing problems, this PR "seems" to work as well as the current `main` branch.

**Pull request merged**
