### PR TITLE
Update DLL and license for virtual serial bridge 

### PR DESCRIPTION
**Pull request by CoryCharlton**
## Description
- Updated HHD Software virtual serial bridge library.
- Update renewed license.

## Motivation and Context

- Fixes nanoFramework/Home#1504

## How Has This Been Tested?
Manually.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [X] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [X] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by CoryCharlton** [comment]
Once a new `nanoclr` is available I'll retest  https://github.com/nanoframework/Home/issues/1504 and see if the VS extension works correctly.

**Comment by josesimoes** [comment]
Our OSS license has expired.
I've reached out to the publisher asking an updated one for the new version.

**Comment by josesimoes** [comment]
@CoryCharlton just pushed the new license file.
Tested locally and it seems OK. Please double check.

**Comment by CoryCharlton** [comment]
@josesimoes the new license seems to resolve the outstanding UAC issue issue I was having. This is ready to be merged.

**Comment by josesimoes** [comment]
Perfect! Thanks for cross checking. Let's go for it.

**Review by josesimoes — APPROVED** [review]

**Pull request merged**
