### PR TITLE
Adds SQLite souce

### PR DESCRIPTION
**Pull request by networkfusion**
## Description
nanoFramework needs a database storage mechanism, SQLite is embedded compatible, and so far no other "open source" compatible format is worthy.

It is hoped that the community will take up the challenge to complete, although a sample managed layer is available at https://github.com/networkfusion/lib-nanoFramework.System.Data.SQLite

This PR intends to add the necessary support (although glue layer need populating).
Example for the native implementation available at: https://www.tutorialspoint.com/sqlite/sqlite_c_cpp.htm

## How Has This Been Tested?
No tests yet, although the unmanaged test layer is included with source.

## Types of changes
- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by josesimoes** [comment]
👏 looking good!

I would set this to be a class library and drop the Interop layer to increase performance. This will be a core feature anyway, so...

**Comment by networkfusion** [comment]
@josesimoes I would like to start working on this again soon, but need some pointers about where to add the interface (since as far as I can see, it will be direct calls from the managed side without an abstraction layer). Tips welcome, so we can get this feature closed off...

**Comment by josesimoes** [comment]
@networkfusion let's talk about this on Discord, OK?

**Comment by AdrianSoundy** [comment]
Currently updating the lib-nanoFramework.System.Data.SQLite

**Pull request merged**
