### PR TITLE
Nxp Gpio update to use a standard interface and enable interrupts

### PR DESCRIPTION
**Pull request by AdrianSoundy**
## Description
This is the changed low level GPIO driver for the NXP target.
Ported existing code to new layout and added the handling for interrupts.

## How Has This Been Tested?
This hasn't been tested on a target board 

Some methods for saving/finding/deleting gpio state information have been unit tested in a different environment so hopefully ok.
 

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: adriansoundy <adriansoundy@gmail.com>

### CODE REVIEW

**Comment by MateuszKlatecki** [comment]
In the Debug version, the outputs work. Input reading also works. 
However, GpioPinValueChangedEvent is not triggered. From what I see it lacked configuration and enable interrupt for pins.
Unfortunately, in the optimized version, the program falls into HardFault right after starting.

**Comment by josesimoes** [comment]
@MateuszKlatecki thank for testing this.

Any chance you can look into adding those missing configurations for the interrupts? 😁 

The same goes for the hard fault. Considering that you're the only one with that board and that it's impossible to even start debugging that hard fault without actually running it on the hardware... 😉

**Comment by josesimoes** [comment]
Are we OK with this?

**Comment by josesimoes** [comment]
@MateuszKlatecki waiting for your approval 😉

**Comment by AdrianSoundy** [comment]
Yes ok now. Issue was GLobal_Lock fixed in PR #1518

**Pull request merged**
