### PR TITLE
fix for USB connection issues with F769I

### PR DESCRIPTION
**Pull request by networkfusion**

### CODE REVIEW

**Comment by piwi1263** [comment]
You're sure you want the OGT1, OTG2 settings in mcuconf.h in both booter and clr different ?

**Comment by josesimoes** [comment]
If there is a good reason for this, there is nothing fundamentally wrong with it...
Booter and CLR can behave differently if required. That's why they are designed to be completely separate entities. @networkfusion will tell if that's on purpose or not.

**Comment by piwi1263** [comment]
That's why I asked.

**Comment by networkfusion** [comment]
Kind of because the St port is listed as FS... But i have disabled it in my current code as well as changing some of the static fields to be USB2. I will push it when at my laptop. It doesn't fix the fact that deployment still fails though...

**Comment by networkfusion** [comment]
hoping I have rebased correctly... please let me know if not?!

**Pull request merged**
