### PR TITLE
Fix serial com Store() delay

### PR DESCRIPTION
**Pull request by josesimoes**
## Description
- Correct code for events handling that was causing a delay equal to the timeout when storing data in the Tx stream

## Motivation and Context
- Fixes nanoframework/Home#282

## How Has This Been Tested?
- SerialComm app from samples repo

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Signed-off-by: José Simões <jose.simoes@eclo.solutions>

### CODE REVIEW

**Comment by josesimoes** [comment]
@AdrianSoundy I went and try to fix this in the ESP32 code but it seems that the execution events are not being used in the Store() and Read() calls there...

**Comment by MikroBusNet** [comment]
This does not fix the issue in the description but hopefully this one instead : nanoframework/Home#283  
:)

**Comment by AdrianSoundy** [comment]
The esp32 serial driver still needs updating to use evenrwaits for the read & store. Will update once finished with in tial network stuff.

**Comment by MikroBusNet** [comment]
The changes here do not fix the issue. I am reopening it.

**Pull request merged**
