### PR TITLE
Rework ESP32 serial implementation

### PR DESCRIPTION
**Pull request by josesimoes**
## Description
- Add new function Esp32_SetMappedDevicePins.
- Add new enum with serial pins indexes.
- Replace "magic numbers" in serial gpio arrays with defines and enums.
- Add NF_PAL_UART struct to ESP32 serial device.
- Rework Store and Read implementations to properly handle timeout and non blocking execution.
- Fix get_BytesToRead to return count of elements in the input stream buffer.
- Remove COM1 from the available UARTS.

## Motivation and Context
- Fixes issues with using default UART GPIOs that are shared with serial flash and PSRAM.
- Addresses nanoFramework/Home#610.
- Addresses nanoFramework/Home#612.

## How Has This Been Tested?
- Serial sample. Latest version adjusted to work with ESP32.
- TX is working. 
- RX is failing.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: josesimoes <jose.simoes@eclo.solutions>

### CODE REVIEW

**Comment by josesimoes** [comment]
@AdrianSoundy receiving simply doesn't work.
I've tested the code with STM32F769 and it's working. 
Sending text is not a problem. Output performs as expected.
Receiving simply does not work. I've put a logic analyser at RX pin and it picks up the chars being send from the serial terminal.

I'm using an FTDI serial to USB cable. Same as with STM32F769.
Tried several baud rates, GPIOs, UART1 & 2. Task pinned to core or not. No matter what nothing makes the UART event fire. Never. Almost sure I'm missing something obvious...

**Comment by AdrianSoundy** [comment]
I have tried testing this and i am not getting any receive events. Output is working.
Maybe this is the same problem as with previous version.  Maybe related to IDF 3.3.1 will try and check.

**Comment by AdrianSoundy** [comment]
Using a process of elimination found that if i put a delay for 10 secs at the end of  Native_Init and some logging in the event handler the RX data events will be fired until the delay ends and that data is picked up in managed code. After returning back to CLR the events stop. Doesn't seem to call anything in serial device to stop it. Still looking at it.

**Comment by AdrianSoundy** [comment]
I have found the problem. It's due to calling uart_param_config() after driver has been installed. It resets the UART and stops the events. I have tested a change with calling individual uart_set functions and now seems to be working and we are now getting RX data :-)

There are still some other issues around dispose that cause exceptions when restarting. Still looking in to that. I don't think we need the extra RX ring buffer as the driver has already got its own ring buffer. We probably need TX ring buffer as driver one doesn't allow you to find out what has been sent and you can also disable the driver TX ring buffer.  

Probably easier if i do a PR against your repo once i am done.

**Comment by josesimoes** [comment]
> UartTxWorkerTask seems to be started for each store when a long Running operation which is strings over 20 bytes at 9600. Maybe the TX thread should be like RX thread and have a queue. But then serial is so slow that it probably doesn't make a difference.

We really need this to make sure the CPU is relinqusihed back to the execution engine and the TX handled by the thread. Otherwise the C# app just freezes and this can't happen.

**Comment by josesimoes** [comment]
> Do we have a unit test framework we can use for manual unit test ?

Nothing that I can recommend. We really should look into adding this...

**Comment by josesimoes** [comment]
> I have found the problem. It's due to calling uart_param_config() after driver has been installed. It resets the UART and stops the events. I have tested a change with calling individual uart_set functions and now seems to be working and we are now getting RX data :-)

Awesome!! 👏 👏 👏 
Glad that you've found it. 😃 

 
> Looks like problem was caused by the latest IDF upgrade. Change in UART driver.
> 
> There are still some other issues around dispose that cause exceptions when restarting. Still looking in to that. I don't think we need the extra RX ring buffer as the driver has already got its own ring buffer. 

I'm affraid we do, otherwise it's hard to controll the read bytes requested by the Read operation... At least this is what I could find when reworking it. Keep in mind that the it's the Read operation on the C# stream that is in charge.

> We probably need TX ring buffer as driver one doesn't allow you to find out what has been sent and you can also disable the driver TX ring buffer.

Yes we need it. No way around it. Again that's because it's C# stream Store that's in charge.

> Probably easier if i do a PR against your repo once i am done.

I'll open a branch here so you can commit at will.

**Comment by AdrianSoundy** [comment]
I updated driver and now working. This is now in separate PR #1658

**Pull request merged**
