### PR TITLE
Switching MathInternal.Min/Max to managed implementations 

### PR DESCRIPTION
**Pull request by CoryCharlton**
## Description
- Switching min/max to managed implementations in MathInternal.

## Motivation and Context
- Improve performance
- Following nanoframework/CoreLibrary#208.

## How Has This Been Tested?
- On device
- Unit tests

## Types of changes

- [X] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [x] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [X] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [X] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by CoryCharlton** [comment]
This is related to https://github.com/nanoframework/CoreLibrary/pull/208

**Comment by CoryCharlton** [comment]
The unit test failure appears to be a chick and egg problem. The unit tests can't run until this firmware is merged but this firmware can't be merged until the unit tests run :D

**Review by josesimoes — APPROVED** [review]
LGTM!

**Comment by josesimoes** [comment]
> The unit test failure appears to be a chicken and egg problem. The unit tests can't run until this firmware is merged but this firmware can't be merged until the unit tests run :D

Yes. That's a _thing_ with these types of changes.

**Comment by josesimoes** [comment]
@CoryCharlton unless there is active work on the PR, don't worry on continiously merging from upstream on the open PRs. This will be done one last time before they are to be merged. Reason: each time there are a bunch of VMs that are spun up for the build pipelines to build all of it, which is a waste of time and resources. 😉

**Pull request merged**
