### PR TITLE
Improve Dockerfiles

### PR DESCRIPTION
**Pull request by networkfusion**
## Description

* Improve layout of commands.
* Improve comments.
* Use latest `hex2dfu` rather than tagged version.
* Fix location of GCC.
* Use python:3.10 container for ESP32 and All builds (rather than ppa repo).
* Add smoke test workflow.
* Use lwIP GH mirror for NXP (fixes TLS issues).
* Use ArduPilot GH mirror by default for ChibiOS src (git SVN is too slow and tempremental).
* Bump dockerfile versions.
* Use ARG for toolchain component versions (so they are only used in one place).

## Motivation and Context

* Improve maintainability.
* Ensure Dockerfiles are valid and working before publishing (runs check on PR only).

## How Has This Been Tested?

New (smoketest) workflow.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [x] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by networkfusion** [comment]
NOTE: I would like to question whether `ENV ESP_PATCH_VER=esp-2021r2-patch5-8.4.0` is still correct?!

**Comment by josesimoes** [comment]
> NOTE: I would like to question whether `ENV ESP_PATCH_VER=esp-2021r2-patch5-8.4.0` is still correct?!

Yes. That's the latest version in the IDF version we're using.

 
> AND: whether the hack for Python 3.10 is still required (or use `python:3.10` as the docker image as an alternative).
Not sure which hack you are referring to, but 3.10 it's the last usable version this IDF allows. Above that, things get totally messed up because of the dependencies they have which are waaaay old and some even deprecated or with security flaws.

**Comment by Ellerbach** [comment]
> AND: whether the hack for Python 3.10 is still required

That I really don't remember why...

**Comment by networkfusion** [comment]
@Ellerbach @josesimoes I hope that this PR is acceptable. It is a little wider in range than I hoped and given issues I had recently (as shown by the workflow runs), decided it was time to add a smoke test.

It will help before #2816 is merged, as it adds multiple improvements to ensure builds and tests against them.

(TI currently commented out as broken somewhere (and known)).

**Comment by networkfusion** [comment]
Linked to #2832

**Pull request merged**
