### PR TITLE
Fix PWM deviceSelectorString

### PR DESCRIPTION
**Pull request by doingnz**
## Description
Insufficient space allocated when char deviceSelectorString[30] #ifndef STM32F0XX is true as there will be 7 timer strings "TIM1,TIM2,TIM3,TIM4,TIM5,TIM8,TIM9", each 5 char long. Current allocation is 30 when 35 is required. 

I suggest we let the compiler figure out the maths and suggest  char deviceSelectorString[7 * 5 + 1] = { 0 };

## Motivation and Context
Fix bug.

## How Has This Been Tested?
Source code review. 

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by doingnz** [comment]
I edited in GitHub for quick fix. 

Someone should review all the other places similar method used to calc list of devices.

An alternative approach is let the compiler concat the strings and avoid the overhead and bugs at runtime.  
```
    static char deviceSelectorString[] = ""
#if STM32_PWM_USE_TIM1
                                         + "TIM1,"
#endif
#if STM32_PWM_USE_TIM2
                                         + "TIM2,"
#endif
#if STM32_PWM_USE_TIM3
                                         + "TIM3,"
#endif
#ifndef STM32F0XX
#if STM32_PWM_USE_TIM4
                                         + "TIM4,"
#endif
#if STM32_PWM_USE_TIM5
                                         + "TIM5,"
#endif
#if STM32_PWM_USE_TIM8
                                         + "TIM8,"
#endif
#if STM32_PWM_USE_TIM9
                                         + "TIM9,"
#endif
#endif
        ;
```

Yet another alternative is define the string in a target file as is used for other hw devices like I2C, SPI etc... 
e.g. in a file targets\ChibiOS\NETDUINO3_WIFI\target_windows_devices_pwm_config.h

**Comment by josesimoes** [comment]
> An alternative approach is let the compiler concat the strings and avoid the overhead and bugs at runtime.
> 

I like this approach better. It puts the burden on the machine. Less error prone. 😉 
Can you please change it to this one?

**Comment by doingnz** [comment]
I agree the machine should do the work. 

We can then also get rid of the #ifndef STM32F0XX/#endif as the selected timers are in mcuconf.h

**Comment by doingnz** [comment]
The list of possible timers on some devices is much more than currently listed here.

I have left list as is to simply fix the current bug.

**Review by josesimoes — APPROVED** [review]
Nice catch! Thanks for the fix.

**Pull request merged**
