### PR TITLE
Add partition table for 32MB ESP32_S3 targets

### PR DESCRIPTION
**Pull request by AdrianSoundy**
## Description

Add partition table for 32MB S3 flash targets.

- Updated build to create 32MB partition table for S3 targets
- Remove comments about mapping issues over 3.5MB as not relevant to S3
- Adjusted all deployment area to be same for 8.16 & 32MB partition table
- Made SPIFFS size 8MB for 32MB flash. This will take a while to initialize when firmware flashed
- Updated tasks template to give 32MB flash option

## Motivation and Context
- Fixes nanoFramework/Home#1343

## How Has This Been Tested?

Tested 16MB partitions locally with 10MB spiffs drive. Write 8MB file OK then read contents OK.
Unable to test 32MB 

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

## Summary by CodeRabbit

- **New Features**
  - Added support for a 32MB flash size option in the configuration settings.
  - Implemented a new conditional block to generate a partition table for ESP32_S3 with a 32MB flash size.

### CODE REVIEW

**Comment by AdrianSoundy** [comment]
@josesimoes 
Getting a funny unit test error on this PR.

Not sure why as not much changed.

**Comment by AdrianSoundy** [comment]
@josesimoes 
Seems to be failing on corlib unit tests.  Should I just merge this?

**Comment by josesimoes** [comment]
@AdrianSoundy yes go for it, this failure is unrelated with these changes for sure.

**Comment by josesimoes** [comment]
@AdrianSoundy I've replaced the label with config and build as these changes are related with the build and what it produces, not enhancing anything in the code. 😉

**Pull request merged**
