### PR TITLE
Add support for ST_NUCLEO144_F746ZG ChibiOS board

### PR DESCRIPTION
**Pull request by josesimoes**
- add files to add support for this board
- add CMake modules to add support for STM32F7 series
- update CMake for ChibiOS to find/support board files located in community overlay and target folders

Signed-off-by: José Simões jose.simoes@eclo.solutions

### CODE REVIEW

**Comment by josesimoes** [comment]
😃

**Comment by piwi1263** [comment]
Once this all works for the F7, can #28 be closed too ? @Becafuel 

Oh, and for your information, somebody in the <the-name-not-to-be-mentioned-here> github area managed to get the F7 to speed up 6-7 times, now THAT is interesting. I choose not to x-link that but you look at issue 535 ...

**Comment by josesimoes** [comment]
> Once this all works for the F7, can #28 be closed too ? @Becafuel

That one is related with using the ST Cube MX HAL drivers. So it's not related.

>  in the 'name-not-to-be-mentioned-here' area managed to get the F7 to speed up 6-7 times

We are looking into that so this will be real here too. Out of the box! 😉

**Comment by cw2** [comment]
Regarding F7 vs. F4 speed, IMHO at least half of that is F7 caches (which would be consistent with my results).

It would be nice to know details (i.e. what exactly was measured and how), but I think the odds are low - nothing against the author personally, but he made similar claims/promises before and never released anything (I remember him from Netduino forums, he usually said "...will be open source when ready", which never happened).

Of course there are areas in NETMF that could be improved in terms of speed/performance, but I am a little bit suspecting the author to simply cut things he does not need for his particular use case or make changes that work only with a particular hardware (which is not inherently wrong). But without the information, this is only my personal speculation...

**Comment by cw2** [comment]
We should be able to run ChibiOS testsuite to get credible results.

**Pull request merged**
