### PR TITLE
⏳ add helper class for ESP32 pins

### PR DESCRIPTION
**Pull request by Dweaver309**
## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: GITHUB_USER <GITHUB_USER_EMAIL>

### CODE REVIEW

**Comment by Dweaver309** [comment]
I wrote it to help me remember the default pins. Jose thought it would be
useful. If you feel it is not needed I would agree with you.
Change the code however you  want or don't include it .

Thanks for the feedback

**Comment by josesimoes** [comment]
@AdrianSoundy I was the one suggesting @Dweaver309 to add this, following what is there in STM32.

I understand that EPS32 pins can be configured on-the-fly. The same happens (with less flexibility) on STM32. The point here is to have a mapping with more friendly names for the pins when one is coding.

Equivalent helper classes exist for STM32 and they are useful, specially for developers that are jumping in.

Considering the above, do you have any suggestions on making this more "developer friendly"? 😉

**Comment by josesimoes** [comment]
@Dweaver309 we are giving this some thought internally and thinking on how this pin remapping can be improved even further.

**Comment by Dweaver309** [comment]
Thanks for improvements in advance!

**Comment by AdrianSoundy** [comment]
Started adding this to Hardware.Esp32

**Comment by AdrianSoundy** [comment]
I have been looking at this but there is a problem.
The pin assignments are not fixed so you can't have a simple constant for the definition of say a SPI.Mosi pin which means you end up with a function for every pin as it has to get the current pin assignment. This will add a lot of mostly unused code to the assembly.

So what i have decided to just limit the change t a new function :-
 public static int GetFunctionPin(DeviceFunction function)

This will return the current pin assignment for any device pin.
I will extend it to include ADC which is currently missing, but these are fixed pins.

**Comment by AdrianSoundy** [comment]
This can be closed once Esp32 hardware update #1392 is closed and update to 
lib-nanoFramework.Hardware.Esp32
@Dweaver309

**Pull request closed without merging**
