### PR TITLE
Improve lwIP init

### PR DESCRIPTION
**Pull request by josesimoes**
## Description
- Call to tcpip_init is now done with handler to receive notification of completion.
- Add semaphore to wait for TCP init complete before moving forward with network and sockets init.
- Fix network interface close by adding mac stop call.
- Rename function for coherency.

## Motivation and Context
- Intermittent issues with network init, in particular when using DHCP. DHCP offer sometimes was missed by stack.
- Need to wait from lwIP init complete before moving with sockets and network init.
- Workflow now follows this.
- ESP32 lwIP implementation is already following this, so we now have all platforms aligned.

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by josesimoes** [comment]
@MateuszKlatecki please review and confirm the NXP implementation. Thanks!

**Comment by networkfusion** [comment]
I was just testing this on my orgpal3, and although there are positive improvements, I seem to have issues with SD cards, specifically reading files:

```
using (FileStream fs = new(file, FileMode.Open, FileAccess.Read))
{
    var success = false;
    while (!success)
    {
        try
        {
            var buffer = new byte[fs.Length];
            fs.Read(buffer, 0, (int)fs.Length);
            Debug.WriteLine(Encoding.UTF8.GetString(buffer, 0, buffer.Length));
...
```
It is a positive improvement, but please test before merge.

**Comment by josesimoes** [comment]
> I was just testing this on my orgpal3, and although there are positive improvements, I seem to have issues with SD cards, specifically reading files
This is only touching lwIP and network boot... I don't see how can this affect SD Card... 🤔 



> It is a positive improvement, but please test before merge.
This has been under extensive testing during the past few days. With STM32F769 boards.

**Comment by networkfusion** [comment]
> > I was just testing this on my orgpal3, and although there are positive improvements, I seem to have issues with SD cards, specifically reading files
> > This is only touching lwIP and network boot... I don't see how can this affect SD Card... 🤔
> 
> > It is a positive improvement, but please test before merge.
> > This has been under extensive testing during the past few days. With STM32F769 boards.

🤔 I am not saying it is the cause, but in my program case, can see the file buffer has received the correct number of bytes, but not able to receive them... Perhaps DMA issues with alignment and thought I would mention.

**Comment by networkfusion** [comment]
> > > I was just testing this on my orgpal3, and although there are positive improvements, I seem to have issues with SD cards, specifically reading files
> > > This is only touching lwIP and network boot... I don't see how can this affect SD Card... 🤔
> > 
> > 
> > > It is a positive improvement, but please test before merge.
> > > This has been under extensive testing during the past few days. With STM32F769 boards.
> 
> 🤔 I am not saying it is the cause, but in my program case, can see the file buffer has received the correct number of bytes, but not able to receive them... Perhaps DMA issues with alignment and thought I would mention.
> 
> I will kill my devcontainer and rebuild/test.

Just wanted to note that I have now fully tested this with debug firmware and the issue is still present on the main branch, so have no issues with this PR.

**Comment by josesimoes** [comment]
@MateuszKlatecki any chance you can review this?

**Comment by MateuszKlatecki** [comment]
> @MateuszKlatecki any chance you can review this?

LGTM

**Pull request merged**
