### PR TITLE
Work on Convert.cs

### PR DESCRIPTION
**Pull request by MikroBusNet**
Implementation of native methods using ChibiOS features.

Signed-off-by: Christophe Gerbier <christophe@mikrobusnet.org>

### CODE REVIEW

**Comment by MikroBusNet** [comment]
This PR should be merged after the other PRs otherwise it will not compile due to the Array.cs correction pending.

**Comment by josesimoes** [comment]
@MikroBusNet seems that you have to do the merge at your end for this PR to move forward...

**Comment by MikroBusNet** [comment]
I knew I should have waited for the other PRs to be merge because of corlib_native.cpp :(

**Comment by MikroBusNet** [comment]
Given the bad PR #85 on nf-class-libraries, I think that this one can be delayed as well.

**Pull request closed without merging**
