### PR TITLE
Update ESP32 build settings to match CI

### PR DESCRIPTION
**Pull request by alberk8**
## Description

- Change ESP32_REV0_BLE to ESP32_BLE_REV0
- ESP_REV0
- ESP_PICO
- ESP_WROVER_KIT
- FEATHER_S2
- KALUGA_1
- Change M5Stack to M5Core

## Motivation and Context
- Aligns the dev container cmake variants with pipeline.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (work on Unit Tests, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by josesimoes — CHANGES_REQUESTED** [review]
Thank for taking care of this. A couple of requests please:
- Remove API_System.IO.FileSystem from everywhere. This is added by the build system as needed. No need to have that in the build options.
- Please format the json. As it is the idents are completely random.
- Remove the TOUCHPANEL_DEVICE option for KALUGA_1 it doesn't have a touch screen.

**Review by alberk8 — COMMENTED** [review]
- Removed all API_SYSTEM.IO.FileSystem => Done
- Format Json => Done
- Remove TOUCHPANEL_DEVICE Option for KALUGA_1 => Done

**Review by alberk8 — COMMENTED** [review]
Add sdkconfig.default_nopsram.esp32 to the SDK_CONFIG_FILE for ESP32_REV0

**Comment by networkfusion** [comment]
Linked to https://github.com/nanoframework/Home/issues/877

**Comment by networkfusion** [comment]
@alberk8 If possible, please can you ensure all of the cmake-variant.json files in the target folder(s) are also aligned.

**Comment by alberk8** [comment]
> @alberk8 If possible, please can you ensure all of the cmake-variant.json files in the target folder(s) are also aligned.

Are you referring to synchronizing to all the ESP32 targets in the azure pipeline?

**Comment by networkfusion** [comment]
> > @alberk8 If possible, please can you ensure all of the cmake-variant.json files in the target folder(s) are also aligned.
> 
> Are you referring to synchronizing to all the ESP32 targets in the azure pipeline?

E.g. https://github.com/nanoframework/nf-interpreter/blob/develop/targets/ESP32/ESP32/cmake-variants.json and https://github.com/nanoframework/nf-interpreter/blob/develop/targets/ESP32/ESP32_S2/cmake-variants.json

**Comment by alberk8** [comment]
> > > @alberk8 If possible, please can you ensure all of the cmake-variant.json files in the target folder(s) are also aligned.
> > 
> > 
> > Are you referring to synchronizing to all the ESP32 targets in the azure pipeline?
> 
> E.g. https://github.com/nanoframework/nf-interpreter/blob/develop/targets/ESP32/ESP32/cmake-variants.json and https://github.com/nanoframework/nf-interpreter/blob/develop/targets/ESP32/ESP32_S2/cmake-variants.json

Before I go around changing those.  May I know are these cmake.variant for **non dev container** compile?

**Comment by networkfusion** [comment]
> 

Yes, they are the templates used when running the PS scripts (I think)

**Comment by josesimoes** [comment]
> Before I go around changing those. May I know are these cmake.variant for **non dev container** compile?

These cmake-variants template are only being used to generate the "full" cmake-variants in local VS Code installs. With the PS1 that @networkfusion mentioned.

**Comment by alberk8** [comment]
> > Before I go around changing those. May I know are these cmake.variant for **non dev container** compile?
> 
> These cmake-variants template are only being used to generate the "full" cmake-variants in local VS Code installs. With the PS1 that @networkfusion mentioned.

Do I still need to change that?  
What else do I need to do to get this going?  Thanks.

**Review by josesimoes — APPROVED** [review]
LGTM! Thanks.

**Pull request merged**
