### PR TITLE
Work on PAL events and PAL time

### PR DESCRIPTION
**Pull request by josesimoes**
## Description
- Rename PAL events timer to improve clarity
- Correct bug in Events_WaitForEvents: wrong call to HAL_Time_CurrentSysTicks instead of HAL_Time_CurrentTime because nF ticks are required for HAL_COMPLETION
- Events_WaitForEvents is now using OS Yield instead of OS Wait for a smoother execution
- Rework PAL time by using a timer with callback to schedule HAL_COMPLETION events instead of checking for that on every sysTick
- Remove Time_Interrupt_Hook() from CH_CFG_SYSTEM_TICK_HOOK (not required anymore)
- Rename some argumens to improve clarity
- Clean up code in PAL events for ESP32

## Motivation and Context
- Fixes/Closes/Resolves nanoFramework/Home#NNNN

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

Signed-off-by: josesimoes <jose.simoes@eclo.solutions>

### CODE REVIEW

**Comment by josesimoes** [comment]
@MatthiasJentsch  and @ishvedov appreciate if you could give a try with this PR for ESP32. Thanks!

**Comment by ishvedov** [comment]
@josesimoes working with little performance degradation. Or may be my test faulted.

**Comment by josesimoes** [comment]
OK. Thanks. 👍

**Comment by MatthiasJentsch** [comment]
I'm not sure how to test this. @ishvedov how did you test it?

**Comment by ishvedov** [comment]
@MatthiasJentsch, go to Slack.

**Comment by josesimoes** [comment]
I'm now able to test this with ESP32. It's performing as expected.

**Pull request merged**
