### PR TITLE
Dispose fix for Issue 421

### PR DESCRIPTION
**Pull request by sharmavishnu**
## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: @sharmavishnu

### CODE REVIEW

**Comment by josesimoes** [comment]
Can you please double check this? If no method was removed from the managed class there shouldn't be any difference in the number of method_lookup table...
If the difference is only with the checksum there is no need to update it as the I2C build takes care of that, whenever there is a change.

**Comment by sharmavishnu** [comment]
1. OK. Need to learn what is "squash". Let me get back on this.
2. You are right about the number of entries in the method table. I have noticed that sometimes the number of entries change even when nothing changes in the methods. I am currently running with the recent change, else, when the managed code calls the native code, you get an exception

**Comment by josesimoes** [comment]
> OK. Need to learn what is "squash". Let me get back on this.
Sure! Bing or Google for that and you'll find a bunch of docs and tutorials on this git command.

> You are right about the number of entries in the method table. I have noticed that sometimes the number of entries change even when nothing changes in the methods. I am currently running with the recent change, else, when the managed code calls the native code, you get an exception

The reason for that exception is probably that the calls are _misaligned_ because of that array that is responsible for mapping the C# calls to native functions. 
Suggest that you wipe your bin folder and do a rebuild on the I2C library project.

**Comment by sharmavishnu** [comment]
Closing this after comments from @josesimoes . The branch is anyways refreshed with other changes

**Pull request closed without merging**
