### PR TITLE
Add build option for configuring the amount of SPIRAM to leave free for IDF allocation

### PR DESCRIPTION
**Pull request by mikeoliphant**
## Description
The change allows configuring how much SPIRAM memory is reserved for native allocations on ESP32 devices.

## Motivation and Context
Newer devices have more extended memory. Previously, only 256K was reserved for native allocations. This is restrictive - particularly for graphics purposes - on devices that have 4MB of extended memory. This change makes this reserved memory amount configurable by target. It also changes the value for M5Core2 to 1MB. It remains 256K for other targets.

## How Has This Been Tested?
Tested locally on M5Stack Core2.

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by mikeoliphant** [comment]
I conservatively set the M5Core2 allocation to 1MB - but that is probably still too low (at least from my perspective). It seems like most memory-intensives objects (bitmaps, audio data, etc.) should be allocated and manipulated in native code.

**Comment by JORGEGO** [comment]
Any estimated date to fix this issue...? Thanks

**Comment by mikeoliphant** [comment]
I agree on the "ESP32_", but I think the term "native" makes sense, as it is explicitly about reserving memory for native use that would otherwise be allocated to the managed heap.

**Comment by josesimoes** [comment]
That's a point of view, sure. But everything here is "native" 😅 .... to support "managed" and make the magic happen.
I believe `IDF_ALLOCATION` make that clarification that you're looking for. As it's stating that this chunk of memory is to be used (from SPIRAM) for  IDF to use when malloc_ing_ .

**Comment by mikeoliphant** [comment]
I don't have strong feelings about the name - ESP32_SPIRAM_FOR_IDF_ALLOCATION  is fine. Making the change now.

**Review by josesimoes — APPROVED** [review]

**Comment by alberk8** [comment]
I have just tested the latest build with this change.  It looks like the Graphics memory allocation is still not taking up the memory allocated to it via the `ESP32_SPIRAM_FOR_IDF_ALLOCATION`   [code](https://github.com/nanoframework/nf-interpreter/blob/e8aa94e8eaeb92071319569b2b12b051852a9a6e/targets/ESP32/ESP32/nanoCLR/nanoFramework.Graphics/Graphics_Memory.cpp#L54)

```
M5Core2.InitializeScreen();

var bitmap = DisplayControl.FullScreen;
Debug.WriteLine("After Bmp 1");

// will fail on the next line
var bitmap1 = new Bitmap(320, 240);
Debug.WriteLine("After Bmp 2");

Debug.WriteLine("Done");
Thread.Sleep(Timeout.Infinite);
```

**Comment by mikeoliphant** [comment]
@alberk8 Your code crashes for me as well.

With the default allocation of 320x240x4, there should be *exactly* just enough graphics memory for two fullscreen bitmaps.

I dug into it a bit, and I *think* the bitmap allocation code may have a bug that is allocating twice as much memory as it should.

For now, you can allocate more memory by doing:

Screen screen = new Screen(320 * 240 * 8);    // or however much you want (up to the current 1MB limit).

instead of:

M5Core2.InitializeScreen();

**Comment by alberk8** [comment]
I end up doing this, where it is enough to allocate 3 full bitmap screen.  

`M5Core2.InitializeScreen( (320*240*4) * 3);`

**Comment by alberk8** [comment]
> @alberk8 Your code crashes for me as well.
> 
> With the default allocation of 320x240x4, there should be _exactly_ just enough graphics memory for two fullscreen bitmaps.
> 
> I dug into it a bit, and I _think_ the bitmap allocation code may have a bug that is allocating twice as much memory as it should.
> 
> For now, you can allocate more memory by doing:
> 
> Screen screen = new Screen(320 * 240 * 8); // or however much you want (up to the current 1MB limit).
> 
> instead of:
> 
> M5Core2.InitializeScreen();

Could the allocation be to accommodate 32bit bitmap?

**Comment by mikeoliphant** [comment]
> Could the allocation be to accommodate 32bit bitmap?

That is what I initially thought, but it is something else that I haven't been able to quickly figure out. I'll look into it some more tomorrow.

Regardless, it is a pre-existing issue not related to this PR so maybe continue this discussion on discord?

**Pull request merged**
