### PR TITLE
Updating System.IO.FileSystem checksum

### PR DESCRIPTION
**Pull request by CoryCharlton**
## Description
- Updating System.IO.FileSystem checksum.

## Motivation and Context
The current Nuget library has a different checksum than the firmware.

## How Has This Been Tested?
- Manually

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [X] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [X] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved file system stability and performance by updating internal assembly data.

### CODE REVIEW

**Comment by CoryCharlton** [comment]
Not sure why this is out of sync but I might have missed a pending PR.

**Comment by Ellerbach** [comment]
> Not sure why this is out of sync but I might have missed a pending PR.

If you have moved the stubs all up and changed all the files, it's the way to go :-) If you are missing a definition, then things will compile but break at execution.

**Comment by CoryCharlton** [comment]
> > Not sure why this is out of sync but I might have missed a pending PR.
> 
> If you have moved the stubs all up and changed all the files, it's the way to go :-) If you are missing a definition, then things will compile but break at execution.

I meant I wasn't sure who committed changes to System.IO.FileSystem without updating the stubs. 

The current NuGet library is newer than the firmware and updating the stubs here didn't seem to break anything in my testing.

**Comment by AdrianSoundy** [comment]
It doesn't look like previous changes to C# code have required any change to native code. Just look like the signature has changed. So I don't see any reason not to merge this PR.

**Review by AdrianSoundy — APPROVED** [review]

**Pull request merged**
