### PR TITLE
Fixes for case sensitive file systems

### PR DESCRIPTION
**Pull request by kjhughes097**
Fixed up CMake files and source files so the look for the correct case paths
and filenames. Fixed missing path elements for NXP target.

Signed-off-by: Ken Hughes <ken@kapie.com>

Getting the dev container building correctly on a case sensitive filesystem (Linux)

## Description
5 files renamed (case sensitivity)
Many files (CMake and source) had text case changed
Fixed path elements missing from NXP target FreeRTOS source

## Motivation and Context
Dev container builds fail on Linux
- Fixes nanoFramework/Home#692

## How Has This Been Tested?
Manually tested all build targets (MinSizeRel versions with default options of the cmake-variants-DEVCONTAINER.json
VSCode on Ubuntu 20.04

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/nanoframework/nf-interpreter?pullRequest=1832) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/nanoframework/nf-interpreter?pullRequest=1832) before we can accept your contribution.<br/><br/>:x: kjhughes097 [sign now](https://cla.dotnetfoundation.org/nanoframework/nf-interpreter?pullRequest=1832)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/nanoframework/nf-interpreter?pullRequest=1832) it.</sub>

**Review by josesimoes — COMMENTED** [review]
Are you sure about the changes in the FreeRTOS paths? Because the build for this target is green on Azure. Maybe you're using a different branch/version locally... Can you double check please?

**Comment by josesimoes** [comment]
Are you sure we need to change the NXP series name too? if that's the case then this should propagate to the rest of the places where it's used like docs, yamls, etc. I would leave it with the initial "i" upper case...

**Comment by kjhughes097** [comment]
> Are you sure about the changes in the FreeRTOS paths? Because the build for this target is green on Azure. Maybe you're using a different branch/version locally... Can you double check please?

Open the dev contain, select the `MinSizeRel NXP_MIMXRT1060_EVK` target and I get this written into the build directory:
image
All other FreeRTOS based target seem okay (path wise) - so not sure why this is pulling a different path for NXP...

**Comment by kjhughes097** [comment]
> Are you sure we need to change the NXP series name too? if that's the case then this should propagate to the rest of the places where it's used like docs, yamls, etc. I would leave it with the initial "i" upper case...

Looks like a rename of the CMake files `FreeRTOS_iMXRT10xx_sources.cmake` and `FreeRTOS_iMXRT10xx_GCC_options.cmake` to have upper case 'I's should achieve the same thing
I'll modify the PR

**Comment by josesimoes** [comment]
> > Are you sure about the changes in the FreeRTOS paths? Because the build for this target is green on Azure. Maybe you're using a different branch/version locally... Can you double check please?
> 
> Open the dev contain, select the `MinSizeRel NXP_MIMXRT1060_EVK` target and I get this written into the build directory:
> image
> All other FreeRTOS based target seem okay (path wise) - so not sure why this is pulling a different path for NXP...

Interesting... That happening must be because of a different veeaion/branch/tag being pulled.

Can you please check what's been actually cloned and on what state is left the FreeRTOS repo on the build directory? And compare that against what's expected to be there? You can see the version on the cmake on the FreeRTOS folder that's responsible for setting up that step.

**Comment by kjhughes097** [comment]
>Can you please check what's been actually cloned and on what state is left the FreeRTOS repo on the build directory? And compare that against what's expected to be there? You can see the version on the cmake on the FreeRTOS folder that's responsible for setting up that step.

Looks like NXP is the only one that uses `targets/FreeRTOS`. ESP versions use `targets/FreeRTOS_ESP32`. Anyway, I'm not sure of the exact flow, but the `CmakeLists.txt files in the two folders are *completely different*...
The NXP one is doing this:
```
    # sanity check is source path exists
    if(EXISTS "${RTOS_SOURCE_FOLDER}/")
        message(STATUS "RTOS is: FreeRTOS (source from: ${RTOS_SOURCE_FOLDER})")

        # check if we already have the sources, no need to copy again
        NF_DIRECTORY_EXISTS_NOT_EMPTY(${CMAKE_BINARY_DIR}/FreeRTOS_Source/ SOURCE_EXISTS)

        if(NOT ${SOURCE_EXISTS})
            file(COPY "${RTOS_SOURCE_FOLDER}/" DESTINATION "${CMAKE_BINARY_DIR}/FreeRTOS_Source/lib/FreeRTOS")
        else()
            message(STATUS "Using local cache of FreeRTOS source from ${RTOS_SOURCE_FOLDER}")
        endif()

        set(FREERTOS_INCLUDE_DIR ${CMAKE_BINARY_DIR}/FreeRTOS_Source/lib/include)
    else()
        message(FATAL_ERROR "Couldn't find FreeRTOS source at ${RTOS_SOURCE_FOLDER}/")
    endif()
```
specifically setting the `/lib/FreeRTOS/` subpath.

**Comment by josesimoes** [comment]
Let's continue this conversation on Discord please. 😉

**Comment by josesimoes** [comment]
The TI build is failing. Can you please take a look at the build log?

**Comment by Ellerbach** [comment]
We knew there will be additional files with wrong case, so here we are, thanks for finding them. The linter makes it a bit harder to read and follow. @kjhughes097 do you manage to build the exact same target on your own machine?
Logs says there is something broken about the config tool. So that's maybe the issue.

**Review by josesimoes — APPROVED** [review]
LGTM! 
Thanks. 👍🏻 👍🏻

**Review by Ellerbach — APPROVED** [review]
If that build now, and you've adjusted more files to the right case, it is a great news! Thanks a lot! Will PR to have the repo updated. I was waiting for this work to be finished! Thanks!

**Pull request merged**
