### PR TITLE
Remove obsolete variants template

### PR DESCRIPTION
**Pull request by networkfusion**
## Description
* Removes the obsolete file cmake-variants template.
* Updates other files that reference it.

## Motivation and Context
* It is no longer supported (and since replaced with global "presets")
* Requires documentaion update https://github.com/nanoframework/nanoframework.github.io/pull/137 before merge

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [x] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist
- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by networkfusion** [comment]
Works towards https://github.com/nanoframework/Home/issues/877

**Comment by josesimoes** [comment]
This was kept here on purpose until the build options are reconciled with the documentation.

**Comment by networkfusion** [comment]
I guess the PR is valid, Just not ready for merge then 😉

**Comment by networkfusion** [comment]
@josesimoes , Given we are well beyond using this file now, is it time for this PR to be ready?

**Comment by josesimoes** [comment]
@networkfusion I still haven't completed porting/updating these in the docs repo.

**Comment by networkfusion** [comment]
> @networkfusion I still haven't completed porting/updating these in the docs repo.

Can I be of any assistance? Just point me to an example of what needs updating...

**Comment by josesimoes** [comment]
That would be awesome! 😅 
I've been working on this on Eclo branch. Just pushed it to the project one so you can commit at will.
I'll draft a PR there so you can keep working there, possibly completing it.

**Review by josesimoes — CHANGES_REQUESTED** [review]
All good. Just please revert the changes with targets community sub-module as they don't belong to this PR.

**Review by josesimoes — APPROVED** [review]

**Pull request merged**
