### PR TITLE
Fix GC recursive crawling of arrays with referenced objects

### PR DESCRIPTION
**Pull request by antoniofagundes**
## Description
- Replace wrong marking as alive with recursive crawling of array elements.

## Motivation and Context
- Fixes the fix introduced in #2705 

## How Has This Been Tested?
- Running test app with code snippet from https://github.com/nanoframework/nf-interpreter/pull/2705#issuecomment-1651674293

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [x] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Comment by josesimoes** [comment]
@kskowronsk care to take a look at this fix please?

**Comment by MateuszKlatecki** [comment]
I compiled VirtualDevice from the latest main and ran this program:
```cs
using System;
using System.Threading;

namespace GCTests
{
    public class Program
    {
        public static void Main()
        {
            const int n = 65530;
            object[] arrays = new object[n];
            long allocatedArrays = 0;
            for (int i = 0; i < arrays.Length; i++)
            {
                arrays[i] = new object[n];
                for (int j=0;j<n;j++)
                {
                    (arrays[i] as object[])[j] = new byte[8];
                    allocatedArrays++;
                }
                Console.WriteLine($"Allocated arrays: {allocatedArrays}");
            }

            Console.WriteLine("END");

            Thread.Sleep(Timeout.Infinite);
        }
    }
}

```
the program should allocate 65530 * 65530 arrays of 8 bytes - even excluding the overhead for object arrays, this should take ~32GB, so it definitely exceeds the amount of memory available in VirtualDevice (10MB if I'm not mistaken)

After about 10 minutes the program is still running and in the console I see something like that:
```
Allocated arrays: 70903460
Allocated arrays: 70968990
GC: 45msec 3937848 bytes used, 6547404 bytes available
Type 0F (STRING              ):    108 bytes
Type 11 (CLASS               ):    168 bytes
Type 12 (VALUETYPE           ):    312 bytes
Type 13 (SZARRAY             ): 3931872 bytes
   Type 03 (U1               ): 2359080 bytes
   Type 07 (I4               ):     24 bytes
   Type 11 (CLASS            ): 1572768 bytes
Type 18 (FREEBLOCK           ): 6547404 bytes
Type 1A (ASSEMBLY            ):   4236 bytes
Type 1E (DELEGATE_HEAD       ):     36 bytes
Type 22 (THREAD              ):    372 bytes
Type 23 (SUBTHREAD           ):     48 bytes
Type 24 (STACK_FRAME         ):    264 bytes
Type 2B (MEMORY_STREAM_HEAD  ):     36 bytes
Type 2C (MEMORY_STREAM_DATA  ):    396 bytes
Allocated arrays: 71034520
Allocated arrays: 71100050
GC: 58msec 3937848 bytes used, 6547404 bytes available
Type 0F (STRING              ):    108 bytes
Type 11 (CLASS               ):    168 bytes
Type 12 (VALUETYPE           ):    312 bytes
Type 13 (SZARRAY             ): 3931872 bytes
   Type 03 (U1               ): 2359080 bytes
   Type 07 (I4               ):     24 bytes
   Type 11 (CLASS            ): 1572768 bytes
Type 18 (FREEBLOCK           ): 6547404 bytes
Type 1A (ASSEMBLY            ):   4236 bytes
Type 1E (DELEGATE_HEAD       ):     36 bytes
Type 22 (THREAD              ):    372 bytes
Type 23 (SUBTHREAD           ):     48 bytes
Type 24 (STACK_FRAME         ):    264 bytes
Type 2B (MEMORY_STREAM_HEAD  ):     36 bytes
Type 2C (MEMORY_STREAM_DATA  ):    396 bytes
Allocated arrays: 71165580
Allocated arrays: 71231110
GC: 45msec 3937848 bytes used, 6547404 bytes available
Type 0F (STRING              ):    108 bytes
Type 11 (CLASS               ):    168 bytes
Type 12 (VALUETYPE           ):    312 bytes
Type 13 (SZARRAY             ): 3931872 bytes
   Type 03 (U1               ): 2359080 bytes
   Type 07 (I4               ):     24 bytes
   Type 11 (CLASS            ): 1572768 bytes
Type 18 (FREEBLOCK           ): 6547404 bytes
Type 1A (ASSEMBLY            ):   4236 bytes
Type 1E (DELEGATE_HEAD       ):     36 bytes
Type 22 (THREAD              ):    372 bytes
Type 23 (SUBTHREAD           ):     48 bytes
Type 24 (STACK_FRAME         ):    264 bytes
Type 2B (MEMORY_STREAM_HEAD  ):     36 bytes
Type 2C (MEMORY_STREAM_DATA  ):    396 bytes
```

**Comment by kskowronsk** [comment]
Update to my last comment:
Adding COMPUTEREACHABILITY_LOADSTATE(); + COMPUTEREACHABILITY_SAVESTATE(); wil not help. Recursive calls will continue processing stack of higher calls and thus digging deeper into recursion with every array encountered until CPU stack is overflown/depleted.

**Comment by MateuszKlatecki** [comment]
@josesimoes , I suggest reversing the changes made by these 3 PR: #2707 #2706 #2705 - they do more harm than good in my opinion

**Comment by josesimoes** [comment]
For the record: these changes are reverted in #2710

**Pull request merged**
