### PR TITLE
Add Chinese version of README

### PR DESCRIPTION
**Pull request by nnhy**
- Add Chinese version of README.

### CODE REVIEW

**Comment by josesimoes** [comment]
@nnhy are you on Discord? What is your user?

**Comment by nnhy** [comment]
Due to network restrictions, I can't access Discord.
I will promote this project in China. Let's work together to refuel.

**Comment by josesimoes** [comment]
That's most unfortunate...
Not even the Web version?

Sent me an email please. It is more efficient than github issues for having a conversation. 😉

**Comment by nnhy** [comment]
> That's most unfortunate...
> Not even the Web version?
> 
> Sent me an email please. It is more efficient than github issues for having a conversation. 😉

My email is  nnhy@vip.qq.com

In China, we use Wechat to discuss problems instead of chat rooms.
Or use Tencent QQ.

**Pull request merged**
