### PR TITLE
Fix the Checksum of Bluetooth sys_dev_ble_native

### PR DESCRIPTION
**Pull request by alberk8**
## Description

- Fix the checksum miss match between native and manage

## How Has This Been Tested?

Tested on M5Core2 and ESP32_REV3 hardware

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [x] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Review by josesimoes — COMMENTED** [review]
From your Discord message, there was also a change in the method_lookup array....
Can you please tripple check?

**Comment by alberk8** [comment]
Remove one additional line.

**Comment by josesimoes** [comment]
@alberk8 I was updating the BLE pipeline and merge the latest updates. When generating the stubs I don't get any difference from the existing code base.

Can you please double check if you don't have any local changes on your code that are causing this difference?

**Comment by alberk8** [comment]
> @alberk8 I was updating the BLE pipeline and merge the latest updates. When generating the stubs I don't get any difference from the existing code base.
> 
> Can you please double check if you don't have any local changes on your code that are causing this difference?

I have check multiple times and that includes recompiling both the manage and native code.  I am pretty sure that you cannot deploy an app with the bluetooth nuget on to the latest firmware (cloudsmith).

**Comment by josesimoes** [comment]
Something is off then... the build on the pipeline is producing this checksum:
https://dev.azure.com/nanoframework/nanoFramework.Device.Bluetooth/_build/results?buildId=37722&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=86dd5fa6-f51e-57a1-6dd4-575fd75fc7ef

(scrool to line 208)

Do you have your VS extension up to date? Building the C# lib in release?

**Comment by alberk8** [comment]
> Something is off then... the build on the pipeline is producing this checksum: https://dev.azure.com/nanoframework/nanoFramework.Device.Bluetooth/_build/results?buildId=37722&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=86dd5fa6-f51e-57a1-6dd4-575fd75fc7ef
> 
> (scrool to line 208)
> 
> Do you have your VS extension up to date? Building the C# lib in release

It seems that the latest nuget is now working so I am closing this.

**Pull request closed without merging**
