### PR TITLE
Adding support for OEM SKU and Serial Numbers

### PR DESCRIPTION
**Pull request by josesimoes**
## Description
- Add declarations and weak implementation for several platforms.

## Motivation and Context
- Provides a default implementation for device's serial number computed from unique ID contained in a device.
- OEM SKU is provided globally as there is no need to do it per platform.
- The implementation is provided as weak to allow manufacturers to include a strong implementation with their own providers.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [x] New feature (non-breaking change which adds functionality to code)
- [x] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies/declarations (update dependencies or assembly declarations and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [ ] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [ ] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [ ] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

## Summary by CodeRabbit

- **New Features**
	- Introduced new functions to retrieve OEM model SKU and serial numbers, enhancing device identification capabilities.
  
- **Bug Fixes**
	- Minor adjustments to redundant code in network configuration initialization functions for improved clarity.

- **Documentation**
	- Updated comments for clarity in configuration management functions, maintaining existing functionality.

### CODE REVIEW

**Comment by frobijn** [comment]
STM32: The ST_STM32F429I_DISCOVERY and ST_NUCLEO64_F091RC targets do not include `nanoHAL_ConfigurationManager.c` but use `nanoHAL_ConfigurationManager_stubs.c` instead. I've added the three methods to the stub as well. The target does not include the ChibiOS-specific `nanoHAL_ConfigurationManager.cpp` and hence has no serial number. (Compilation of the ST_NUCLEO64_F091RC target fails - region `flash0' overflowed by 22208 bytes - but I can't image that is due to this change as 22K seems to be a lot of code).

The ST_STM32F769I_DISCOVERY target does include `nanoHAL_ConfigurationManager.cpp`. Copied the code for the unique device ID. Cannot test it as I don't have such a MCU.

**Comment by frobijn** [comment]
Silabs Giant Gecko: added the device unique ID code. Build of SL_STK3701A and SL_STK3701A_REVB succeeds. Don't have the device, cannot test the code any further.

**Review by josesimoes — COMMENTED** [review]
@frobijn just pushed a couple of minor changes. 
It looks good. 
OK to merge?

**Comment by frobijn** [comment]
@josesimoes LGTM!

**Pull request merged**
