### PR TITLE
Fix lazy init and prevent un-necessary calls to NativeInit

### PR DESCRIPTION
**Pull request by sharmavishnu**
Stub changes due to change in I2C core library

## Description
Everytime "I2cDevice.FromId" method is called, the "NativeInit" method gets called. This method should be called only once per I2C bus. This fix ensures that NativeInit is called only when a new I2C bus is used in managed code

## Motivation and Context

1. Improve code
2. Another attempt to fix I2C hang issue as reported in nanoframework/Home#416 and nanoframework/Home#424

## How Has This Been Tested?

Tested with HTU21D I2C sensor. So far have been able to debug multiple times with no I2C hang.
## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

Signed-off-by: @sharmavishnu

### CODE REVIEW

**Comment by josesimoes** [comment]
@sharmavishnu could you please rebase your branch on "upstream/develop" so this PR isn't showing all these unrelated commits?

**Comment by sharmavishnu** [comment]
1. I have rebased my fork with the upstream. I still see those older commit messages. Can you point me to the right reading material on the internet to fix this
2. I have pushed same changes to ESP32, but do not have a board with me to check.

**Comment by josesimoes** [comment]
@sharmavishnu you are submitting the PR from your develop branch. That causes all sorts of issues when updating from upstream.
Lacking a better (or detailed tutorial) suggest that you follow our [contribution workflow](https://github.com/nanoframework/Home/blob/master/docs/contributing/contributing-workflow.md#suggested-workflow).

Basically:
1. Leave develop branch alone and use it to update from upstream. This is you safety net in case you need to get back, revert or start a new branch.
2. Work from and submit PRs from features branches. You can isolate work, pull from upstream-develop, rebase and keep a clean history.

**Comment by josesimoes** [comment]
I'm opening a branch for this PR to fix the commits and remove the changes.txt file and merge from there.

**Pull request merged**
