### PR TITLE
Added simple bitmap rectangle drawing methods for more common operations

### PR DESCRIPTION
**Pull request by mikeoliphant**
## Description
This PR adds simple rectangle drawing methods for more common operations

## Motivation and Context
Currently the Bitmap class provides only one DrawRectangle method that has a lot of parameter. This PR adds a number of simpler methods that correspond to more common use cases.

The new managed methods can be seen more easily in the corresponding managed PR:

https://github.com/nanoframework/nanoFramework.Graphics/pull/108

## How Has This Been Tested?
Tested locally on M5Core2.

## Types of changes

- [x] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [ ] New feature (non-breaking change which adds functionality to code)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dev Containers (changes related with Dev Containers, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist

- [x] My code follows the code style of this project (only if there are changes in source code).
- [ ] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [x] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.
- [x] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).

### CODE REVIEW

**Review by Ellerbach — APPROVED** [review]
Thanks for the addition. Looks good to me

**Review by josesimoes — APPROVED** [review]
LGTM! 

(just waiting for the new checksum)

**Comment by mikeoliphant** [comment]
Is there anything else needed for this PR? It is good-to-go from my end.

**Review by josesimoes — APPROVED** [review]
LGTM!
(apologies for letting this one slip after your commit with the checksum)

**Comment by mikeoliphant** [comment]
No worries - thanks!

**Pull request merged**
