### PR TITLE
Updates GCC toolchain to 8 2019 q3 

### PR DESCRIPTION
**Pull request by networkfusion**
- Removes depreciated structure-size-boundary
- Closes nanoFramework/home#443. 

local build still has an error

image

### CODE REVIEW

**Comment by josesimoes** [comment]
Not sure if this can be simply removed. It's used to align the CLR structs and that's related with managed heap and gc calculations.

**Comment by networkfusion** [comment]
Just going by https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html#ARM-Options

image

I am not sure what can replace it though...

**Comment by josesimoes** [comment]
Yeap... I'm fearing this since it popped in the last gcc update attempt... 😱
For now it's only a warning, we can always add an exclusion for it in the build. But this has to be addressed sonner rather than later.

**Comment by networkfusion** [comment]
Interesting to note: https://www.mail-archive.com/gcc-patches@gcc.gnu.org/msg169032.html

It seems that the option has been removed, but it defaults to 8 anyway (which is what we use), so the option may be a red herring on the actual issue...

**Comment by networkfusion** [comment]
Also, it seems that using -Wno-deprecated does not work (tried). https://stackoverflow.com/questions/56829875/how-to-suppress-warning-that-gcc-option-is-deprecated

**Comment by josesimoes** [comment]
@networkfusion that's great that the "new" default is exactly what we need and, even further, that's the industry standard. 😉

**Comment by josesimoes** [comment]
GCC toolchain 7z file now on Bintray.

**Comment by josesimoes** [comment]
Build error with incompatible declarations fixed with #1408.

**Comment by josesimoes** [comment]
Improvements in image size (SMT32F769I-DISCO)

* nanoBooter: was 10924 B is now 10900 B (less 24B)
* nanoCLR: was 427544 B is now 422940 B (less 4604B ~2%)

**Pull request merged**
