### PR TITLE
Update Hardware.Esp32.Rmt implementation

### PR DESCRIPTION
**Pull request by MrCSharp22**
## Description

- Update native implementation following change in API to align with ESP32 IDF API.

## Motivation and Context
- Update native code following nanoframework/nanoFramework.Hardware.Esp32.Rmt#56.

## Types of changes

- [ ] Improvement (non-breaking change that improves a feature, code or algorithm)
- [ ] Bug fix (non-breaking change which fixes an issue with code or algorithm)
- [x] New feature (non-breaking change which adds functionality to code)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)
- [ ] Dependencies (update dependencies and changes associated, has no impact on code or features)
- [ ] Unit Tests (add new Unit Test(s) or improved existing one(s), has no impact on code or features)
- [ ] Documentation (changes or updates in the documentation, has no impact on code or features)

## Checklist:

- [X] My code follows the code style of this project (only if there are changes in source code).
- [X] My changes require an update to the documentation (there are changes that require the docs website to be updated).
- [ ] I have updated the documentation accordingly (the changes require an update on the docs in this repo).
- [X] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/master/CONTRIBUTING.md) document.
- [X] I have tested everything locally and all new and existing tests passed (only if there are changes in source code).
- [ ] I have added new tests to cover my changes.

### CODE REVIEW

**Review by Ellerbach — APPROVED** [review]
Very nice improvement with the managed part. And code is easy to read. Hard for me to tell if all the steps as correct but approving anyway as I know you've been intensively testing all this! And we can always adjust in case of problem. I'll have to update quite a few bindings!

**Comment by josesimoes** [comment]
@MrCSharp22 please take a look at the last two commits on the PR:
f0bba71
7929920

These refactors where made in ReceiverChannel class only. Please "reproduce" in the other classes.

**Comment by MrCSharp22** [comment]
> Very nice improvement with the managed part. And code is easy to read. Hard for me to tell if all the steps as correct but approving anyway as I know you've been intensively testing all this! And we can always adjust in case of problem. I'll have to update quite a few bindings!

Thanks @Ellerbach. I am happy to work on updating the bindings too. It is on my to do list for this contribution. But I will need your help with testing some of the libs because I don't have those modules/devices. We can work this out on a PR basis. But yes, I will update those bindings so don't worry about that ;)

**Comment by MrCSharp22** [comment]
> @MrCSharp22 please take a look at the last two commits on the PR: [f0bba71](https://github.com/nanoframework/nf-interpreter/commit/f0bba71f82b85099b54477e301b7e8e2e026043e) [8d1b951](https://github.com/nanoframework/nf-interpreter/commit/8d1b951850f1beb47394f3d9c897616ca64ce7b9)
> 
> These refactors where made in ReceiverChannel class only. Please "reproduce" in the other classes.

No problem @josesimoes  and thank you for doing that. I will have a look soon and replicate the changes across.

**Review by josesimoes — APPROVED** [review]
All good! Let have this merged!! 💯

**Pull request merged**
